In [ ]:
# @title Install necessary libraries
!pip install google-genai google-cloud-storage pypdf google-colab
print("Libraries installed.")

Requirement already satisfied: google-genai in /usr/local/lib/python3.12/dist-packages (1.38.0)
Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.12/dist-packages (2.19.0)
Collecting pypdf
  Downloading pypdf-6.1.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: google-colab in /usr/local/lib/python3.12/dist-packages (1.0.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.10.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.38.0)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.11.9)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from google-genai) (2.32.4)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from google-genai) (8.5.0)
Requirement already satisfied: websockets<15.1.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (15.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.11.0 in /usr/local/lib/python3.12/dist-packages (from google-genai) (4.15.0)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (2.25.1)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (2.7.2)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (1.7.1)
Requirement already satisfied: ipykernel==6.17.1 in /usr/local/lib/python3.12/dist-packages (from google-colab) (6.17.1)
Requirement already satisfied: ipyparallel==8.8.0 in /usr/local/lib/python3.12/dist-packages (from google-colab) (8.8.0)
Requirement already satisfied: ipython==7.34.0 in /usr/local/lib/python3.12/dist-packages (from google-colab) (7.34.0)
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.12/dist-packages (from google-colab) (2.2.2)
Requirement already satisfied: jupyter-server==2.14.0 in /usr/local/lib/python3.12/dist-packages (from google-colab) (2.14.0)
Requirement already satisfied: portpicker==1.5.2 in /usr/local/lib/python3.12/dist-packages (from google-colab) (1.5.2)
Requirement already satisfied: tornado==6.4.2 in /usr/local/lib/python3.12/dist-packages (from google-colab) (6.4.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-genai) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-genai) (4.9.1)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel==6.17.1->google-colab) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel==6.17.1->google-colab) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel==6.17.1->google-colab) (0.1.7)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel==6.17.1->google-colab) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from ipykernel==6.17.1->google-colab) (25.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel==6.17.1->google-colab) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel==6.17.1->google-colab) (26.2.1)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel==6.17.1->google-colab) (5.7.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipyparallel==8.8.0->google-colab) (4.4.2)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from ipyparallel==8.8.0->google-colab) (0.4)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.12/dist-packages (from ipyparallel==8.8.0->google-colab) (2.9.0.post0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ipyparallel==8.8.0->google-colab) (4.67.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython==7.34.0->google-colab) (75.2.0)
Collecting jedi>=0.16 (from ipython==7.34.0->google-colab)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython==7.34.0->google-colab) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython==7.34.0->google-colab) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython==7.34.0->google-colab) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython==7.34.0->google-colab) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython==7.34.0->google-colab) (4.9.0)
Requirement already satisfied: argon2-cffi>=21.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (25.1.0)
Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (3.1.6)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (5.8.1)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (7.16.6)
Requirement already satisfied: nbformat>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (0.22.1)
Requirement already satisfied: send2trash>=1.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server==2.14.0->google-colab) (1.8.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->google-colab) (2.0.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->google-colab) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2->google-colab) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->google-genai) (2025.8.3)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0.0,>=4.8.0->google-genai) (1.3.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage) (1.70.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage) (5.29.5)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage) (1.26.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->google-genai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->google-genai) (0.4.1)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi>=21.1->jupyter-server==2.14.0->google-colab) (25.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython==7.34.0->google-colab) (0.8.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=3.0.3->jupyter-server==2.14.0->google-colab) (3.0.2)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server==2.14.0->google-colab) (4.4.0)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (4.25.1)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (3.3.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (6.0.2)
Requirement already satisfied: referencing in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (0.36.2)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (0.1.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (3.1.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.3.0->jupyter-server==2.14.0->google-colab) (2.21.2)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython==7.34.0->google-colab) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython==7.34.0->google-colab) (0.2.13)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-genai) (0.6.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.1->ipyparallel==8.8.0->google-colab) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (1.4.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (2025.9.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (0.27.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (24.11.1)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server==2.14.0->google-colab) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server==2.14.0->google-colab) (2.8)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server==2.14.0->google-colab) (2.23)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (1.2.2)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (1.3.0)
Requirement already satisfied: types-python-dateutil>=2.8.10 in /usr/local/lib/python3.12/dist-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server==2.14.0->google-colab) (2.9.0.20250822)
Downloading pypdf-6.1.0-py3-none-any.whl (322 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.5/322.5 kB 7.4 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 29.6 MB/s eta 0:00:00
Installing collected packages: pypdf, jedi
Successfully installed jedi-0.19.2 pypdf-6.1.0
Libraries installed.

In [ ]:
# @title Import libraries and authenticate
from google import genai
from google.cloud import storage
from google.colab import auth
from google.genai.types import Part, GenerateContentConfig # Import Part for file input
import pypdf
import os
import json
import textwrap # For printing long text nicely
from IPython.display import display, Markdown # For better output formatting

# Authenticate the Colab user for GCP access (like GCS)
print("Authenticating user for Google Cloud access...")
auth.authenticate_user()
print("Authentication successful.")

Authenticating user for Google Cloud access...
Authentication successful.

In [ ]:
# @title Configure Google Cloud Settings and connect Google Cloud Storage
#    Replace with your actual Project ID, Bucket Name, and Prefix (folder)
GCP_PROJECT_ID = "extraction-papers-talhouk2"
GCS_BUCKET_NAME = "tlab-extractionbucket3"
GCS_PREFIX = "papers3" # e.g., "papers/neuroscience/" or "" for root
LOCATION = "us-central1" # location you want to use for data procssing

# Optional: Set project for GCS client (often inferred after auth, but explicit is safer)
try:
    storage_client = storage.Client(project=GCP_PROJECT_ID)
    print(f"Google Cloud Storage client initialized for project '{GCP_PROJECT_ID}'.")
except Exception as e:
     print(f"Error initializing GCS Client: {e}. Trying without explicit project ID.")
     try:
         storage_client = storage.Client()
         inferred_project = storage_client.project
         print(f"Google Cloud Storage client initialized using inferred project '{inferred_project}'.")
         GCP_PROJECT_ID = inferred_project # Update if inferred
     except Exception as e2:
         print(f"FATAL ERROR: Could not initialize GCS Client: {e2}")
         storage_client = None # Ensure it's None if failed

Google Cloud Storage client initialized for project 'extraction-papers-talhouk2'.

In [ ]:
# # @title Model Selection
MODEL_NAME = "gemini-2.0-flash-001"
client = genai.Client(vertexai=True, project=GCP_PROJECT_ID, location=LOCATION)
print(f"Using Gemini model: {MODEL_NAME}")

Using Gemini model: gemini-2.0-flash-001

In [ ]:
##@title Define Entities To Extract
ENTITIES_TO_EXTRACT = {
   #"Title of Paper": "Extract the title of the paper, e.g., POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium",
   # "Author list": "Extract the full list of authors, e.g., DeRycke M, Andersen J.D., Harrington K.M., Pambuccian S.E., Kalloger S.E., Boylan K.L.M., et al.",
   "Histology": "Based on the primary cancer type under study, classify the paper as one of the following: Ovarian (including ovarian cancers with endometrioid histology or arising from endometriosis, such as endometriosis-associated ovarian cancer), Endometrial (only if the primary cancer is located in the endometrium), Both (if both ovarian and endometrial cancers are studied as distinct primary cancers), Neither (if neither is a focus of the study), Do not classify as 'Endometrial' just because of endometrioid histology unless the primary site is explicitly the uterus. Likewise, do not choose 'Both' unless both cancers are discussed as distinct primary diseases.”",
    #"Histology subtype":"""Extract up to 5 distinct histological cancer subtypes discussed in the study, focusing on the most prominently analyzed or referenced.

#Use the following controlled vocabulary only (do not invent new labels):

#Endometrial Cancer

#Endometrioid Endometrial Cancer

##Non-Endometrioid Endometrial Cancer

#Endometrial Serous Carcinoma

#Endometrial Clear Cell Carcinoma

#Uterine Papillary Serous Carcinoma

#Endometrial Mucinous Carcinoma

#Small Cell Carcinoma of the Endometrium

#Malignant Mixed Mesodermal Tumour (carcinosarcoma)

#Not otherwise specified Endometrial Adenocarcinoma

#Endometrioid Ovarian Carcinoma

#Clear Cell Ovarian Carcinoma

#Endometriosis-associated Ovarian Cancer

#Serous Ovarian Carcinoma

#High-Grade Serous Ovarian Carcinoma

#Important:

#Do not confuse Endometrioid Ovarian Carcinoma with Endometriosis-associated Ovarian Cancer, they are distinct subtypes.

#List only the most frequently or centrally analyzed subtypes.

#If more than 5 are mentioned, return the top 5 and add ""Other"" at the end.

#Format your answer as a comma-separated list, e.g.:
#Endometrioid Endometrial Cancer, High-Grade Serous Ovarian Carcinoma, Endometrial Serous Carcinoma, Clear Cell Ovarian Carcinoma, Other""

 # "Publisher":"Extract the publisher, e.g., Gynecol Oncol",
#      "N of total cohort":"Extract the full sample size of the patient cohort that was analysed in the study. Carefully evaluate if multiple cohorts are mentioned and add them up. Return only one number, e.g., 192",
#      "Date of diagnosis":"Extract the date range of when the patients in the cohort received the first diagnosis, e.g., 2005 - 2011",
    # "Primary location of study":"Extract the primary city and country of the study, e.g,. Vancouver, Canada",
    # "Treatments applied in the study": "Extract a detailed summary of all treatments applied to patients in the study. Include initial treatments (e.g., surgery, debulking, salpingo-oophorectomy), chemotherapy (specify neoadjuvant or adjuvant, and agents like platinum-based, taxol, cisplatin), radiation therapy (e.g., external beam, vaginal brachytherapy), hormonal therapy (e.g., megestrol, progesterone IUS), and any targeted or immunotherapies. For each treatment, report the number of patients and percentages if available. State clearly if patients received no treatment. If treatments differ by cancer subtype, report separately. If only general treatment statements are given (e.g., 'all received platinum-based chemotherapy after surgery'), extract those directly. If treatment information is not available, return 'N/A'. Return answers in a structured, itemized format with precise counts and treatment types.",
    # "Analysis":"Extract the technology used to perform the analysis of the primary samples, e.g., IHC TMA",
   # "Analysed Biomarkers":"Extract which biomarkers were analysed in the study, e.g., POLE, p53, MMR, L1CAM, BRCA1. Only extract the top 3 most significant biomarkers, often mentioned in the methods and/or abstract and/or conclusion",
    # "Significant in multivariate (1), univariate (2), or both (3), analysis not significant (4) or unknown (5)":"Determine whether the biomarker or treatment of interest showed statistical significance in univariate analysis, multivariate analysis, both, neither, or if unknown/not reported (codes: 1 = multivariate only, 2 = univariate only, 3 = both, 4 = neither, 5 = unknown), where univariate analysis examines one variable at a time and multivariate analysis adjusts for multiple variables (often described using terms like “Cox regression,” “adjusted for,” or “independent predictor”); if statistical significance is reported without mention of adjustment or multivariate methods, assume univariate analysis.",
    # "Did the identified biomarker or treatment improve prognosis? Prognosis: Improved (1), Worse (2), Both (3), not significant (4), unknown (5)":"Determine the overall effect of the identified biomarker(s) or treatment on patient prognosis and return only one code—1 = improved, 2 = worse, 3 = both (if different subgroups or biomarkers show opposing effects), 4 = no significant effect, 5 = unknown—and if there are mixed effects, return 3 with a brief rationale.",
    # "N histotype":"Extract and explicitly state the histotype composition of the full study cohort. Only report histotypes, such as: Endometrial Carcinoma, Endometrioid Endometrial Carcinoma, Endometrioid Ovarian Carcinoma, Clear Cell Ovarian Carcinoma, Serous Ovarian Carcinoma, etc. Provide exact numbers for each histotype if available. If only percentages are given, calculate and report estimated numbers based on total cohort size. Do not include molecular subtypes, treatment information, or any other clinical characteristics. If no histotype breakdown is provided, return 'N/A'. The output should be limited strictly to histotype cohort composition.",
    # "Was a recent histological review (using 2014 WHO criteria) performed?":"The 2014 WHO criteria specify that the study should provide detailed diagnostic criteria, including histological features, grading and immunohistochemical markers; Or whether there were one or more pathologists who reviewed cases. Determine if this information is available and respond with Yes or No",
    # "5-Year Survival rates (overall survival unless states otherwise)":"Extract the 5-year survival rate, prioritizing overall survival (OS). If OS is not explicitly stated in the main text, check tables, figures, or Kaplan-Meier plots. If only a different survival type is available (e.g., progression-free survival [PFS] or disease-free survival [DFS]), report it and clearly specify the type. Format the result as: 'OVERALL SURVIVAL: 88.3%' or 'PFS: 76.1%'. If no survival data is found anywhere in the paper, return: 'NOT REPORTED'.",
    # "Mean age of participants":"Extract the mean age of participants. If mean is not available, provide the median age. Always specify which is used. Format: MEAN: 42.9, MEDIAN: 45.3. If neither is found, return: AGE NOT REPORTED",
     "% of participants with clinicopathological features (Stage I or II)":"Extract the percentage of study participants with disease Stage I or Stage II tumors, e.g., 97%",
    # "REMARK Critera":"Check if the study explicitly states that it followed REMARK criteria. Look for phrases such as:'according to the REMARK criteria','REMARK reporting criteria','in accordance with REMARK guidelines','REMARK recommendations', or any mention of 'REMARK' in reference to study design or analysis. If such a phrase is found, return: 'Yes', If there is no mention of REMARK criteria or guidelines, return: 'No', Do not infer based on formatting or study structure — rely only on explicit textual mention.",
    # "Conclusion of the study":"Extract a brief summary of the conclusion of the study, e.g., ProMisE subgroups are associated with patient outcome in both univariate and multivariate analysis."

}

In [ ]:
# @title Helper Functions
import re

def list_pdfs_in_gcs(client, bucket_name, prefix):
    """Lists PDF files in a GCS bucket/prefix."""
    if not client:
        print("GCS client not initialized. Cannot list files.")
        return []
    print(f"Listing PDFs in gs://{bucket_name}/{prefix}...")
    try:
        bucket = client.get_bucket(bucket_name)
        blobs = client.list_blobs(bucket, prefix=prefix)
        pdf_files = [f"gs://{bucket_name}/{blob.name}" for blob in blobs if blob.name.lower().endswith(".pdf") and blob.size > 0]
        print(f"Found {len(pdf_files)} PDF files.")
        return pdf_files
    except Exception as e:
        print(f"Error listing GCS files: {e}")
        return []

def extract_entities_with_gemini_uri(gcs_uri, entities):
    """Uses Gemini to extract specified entities directly from a PDF URI."""
    if not gcs_uri or not gcs_uri.startswith("gs://"):
        return {"error": "Invalid GCS URI provided"}

    print(f"  Preparing request for Gemini with URI: {gcs_uri}")
    # Create a Part object representing the PDF file in GCS
    try:
        pdf_file = Part.from_uri(
            file_uri=gcs_uri,
            mime_type="application/pdf" # Crucial for the model to know the file type
        )
    except Exception as e:
        print(f"  Error creating Part from URI {gcs_uri}: {e}")
        return {"error": f"Failed to create Part from URI: {e}"}

    system_instruction=(
        """Analyze the provided PDF file (research paper) and extract the entities given to you in your prompt.
        Provide the output strictly in JSON format with the keys from the prompt.
        If an entity cannot be found or is not applicable, use the value "n/a".
        JSON Output:"""
    ),

    # Construct the prompt, instructing the model to analyze the *provided file*
    print(f"  Calling Gemini API for {gcs_uri}...")
    results = {}

    for entity in entities:
        print(f"  Processing entity: {entity}")
        kg_context = get_kg_context(entity, kg_df)

        # 3b. Add the KG facts to the prompt (if any)
        prompt = f"""
        You are extracting the following entity from the research paper:

        **Entity**: {entity}

        **Instructions**: {entities[entity]}

        Use the following known relationships from a biomedical knowledge graph to help you:
        {kg_context}

        Please return the result strictly in the following JSON format:
        {{
          "{entity}": {{
            "value": "The extracted information",
            "confidence": ["confidence score from 0 to 100 as a percentage", a short one sentence rationale for why the confidence score was given]
          }}
        }}

        If the entity is not found, set "value" to "n/a" and "confidence" to 0.
        """

        # Make the API call with both the prompt and the file Part
        try:
            # The request contains both the text prompt and the file reference
            response = client.models.generate_content(
                model=MODEL_NAME,
                config=GenerateContentConfig(
                    system_instruction=system_instruction),
                contents=[prompt, pdf_file],
                )
            print(f"  Received response from Gemini.")

            # Basic check for response content
            if not response.candidates or not response.candidates[0].content.parts:
                print("  Warning: Gemini response seems empty or malformed.")
                # Check for safety ratings or finish reasons if available
                try:
                    finish_reason = response.candidates[0].finish_reason
                    safety_ratings = response.candidates[0].safety_ratings
                    print(f"  Finish Reason: {finish_reason}")
                    print(f"  Safety Ratings: {safety_ratings}")
                    if response.prompt_feedback:
                        print(f"  Prompt Feedback: {response.prompt_feedback}")
                except (AttributeError, IndexError):
                    pass # Ignore if these attributes don't exist
                return {"error": "Empty or malformed response from API", "raw_response": str(response)}

            extracted_text = response.text
            #print(f"Gemini returned {response.text}")

            # Attempt to parse the JSON response
            try:
                # Clean potential markdown formatting around the JSON
                if extracted_text.strip().startswith("```json"):
                    extracted_text = extracted_text.strip()[7:-3].strip()
                elif extracted_text.strip().startswith("```"):
                    extracted_text = extracted_text.strip()[3:-3].strip()

                result = json.loads(extracted_text)
                for entry in result:
                    results[entity] = result[entry]

            except json.JSONDecodeError:
                print(f"  Warning: Failed to parse JSON response from Gemini.")
                # Log the raw response for debugging
                print(f"  Raw response snippet:\n---\n{textwrap.shorten(extracted_text, width=200, placeholder='...')}\n---")
                #return {"error": "Failed to parse JSON response", "raw_response": extracted_text}
            except Exception as e:
                print(f"  Error processing Gemini response content: {e}")
                #return {"error": f"Error processing response content: {e}", "raw_response": extracted_text}

        except Exception as e:
            # Catch potential API errors (e.g., permission denied on GCS URI, rate limits)
            print(f"  ERROR calling Gemini API for {gcs_uri}: {e}")
            # Check if the error message indicates a permission issue
            if "permission denied" in str(e).lower() or "could not access" in str(e).lower():
                print("  This might be a GCS permission issue. See the note in Cell 3 about granting the 'Storage Object Viewer' role.")
                #return {"error": f"Gemini API call failed: {e}"}
      # Validate that all requested keys are present

    validated_result = {}
    for entity in entities:
        validated_result[entity] = results.get(entity, "n/a") # Default to "Not Found" if key is missing
    return validated_result

In [ ]:
# @title ## KG Integration

from google.colab import files
import pandas as pd

# Upload CSV file
uploaded = files.upload()

# Load the CSV (assumes only one file uploaded)
for filename in uploaded:
    df = pd.read_csv('SemMed.csv')
    print(f"Loaded {filename}")

kg_df = pd.read_csv("SemMed.csv")

Saving SemMed.csv to SemMed.csv
Loaded SemMed.csv

In [ ]:
def get_kg_context(entity, kg_df):
    facts = []
    for _, row in kg_df.iterrows():
        if entity.lower() in row["Node1"].lower() or entity.lower() in row["Node2"].lower():
            fact = f"{row['Node1']} {row['Relationship']} {row['Node2']} (PMID: {row['PMID']})"
            facts.append(fact)
    return "\n".join(facts[:5]) if facts else "None found."

In [ ]:
# @title ## MEREDITH Extractor (S1)

all_results = []
limit = 105

# Initialize the GenAI Client
MODEL_NAME = "gemini-2.0-flash-001"
client = genai.Client(vertexai=True, project=GCP_PROJECT_ID, location=LOCATION)
print(f"Using Gemini model: {MODEL_NAME}")

# Check prerequisites
if not client:
    print("ERROR: GenAI Client not initialized. Please fix configuration.")
elif not storage_client:
    print("ERROR: GCS client not initialized. Please fix configuration.")
else:
    # 1. List PDF files in GCS
    pdf_uris = list_pdfs_in_gcs(storage_client, GCS_BUCKET_NAME, GCS_PREFIX)

if not pdf_uris:
        print("\nNo PDF files found or error listing files. Ensure configuration is correct and files exist.")
else:
        print(f"\nStarting entity extraction for {len(pdf_uris)} PDF files using URIs...")

        # 2. Loop through each PDF URI
        for i, pdf_uri in enumerate(pdf_uris):
          if i > limit:
            break
          print(f"\n--- Processing file {i+1}/{len(pdf_uris)}: {pdf_uri} ---")
          file_result = {"pdf_uri": pdf_uri}

          # 3. Extract Entities using Gemini directly with the URI
          entities_data = extract_entities_with_gemini_uri(pdf_uri, ENTITIES_TO_EXTRACT)
          file_result.update(entities_data)



          if "error" in entities_data:
              print(f"Extraction failed for {pdf_uri}: {entities_data['error']}")
          else:
                print(f"Extraction successful for {pdf_uri}.")

          all_results.append(file_result)

          # Optional: Add a small delay to avoid hitting potential rate limits
          # time.sleep(1) # Sleep for 1 second between requests

        print("\n--- Processing Complete ---")


print(f"\n--- Extracted Information ({len(all_results)} files processed) ---")

# Check if any results were generated
if not all_results:
    print("No results were generated. Please check previous cell outputs for errors.")
else:
    # Iterate and display results for each file
    for result in all_results:
        display(Markdown(f"**File:** `{result.get('pdf_uri', 'N/A')}`")) # Get URI safely
        if "error" in result:
            # Display error message clearly
            display(Markdown(f"  - **Status:** <font color='red'>Error - {result['error']}</font>"))
            # Optionally display raw response snippet if available and useful
            if "raw_response" in result:
                 display(Markdown(f"  - **Raw Response Snippet:**"))
                 display(Markdown(f"```\n{textwrap.shorten(result['raw_response'], width=150, placeholder='...')}\n```"))
        else:
            # Display success and extracted entities
            display(Markdown(f"  - **Status:** <font color='green'>Success</font>"))
            for entity in ENTITIES_TO_EXTRACT:
                value = result.get(entity, "Not Found") # Use .get for safety
                # Format list display (e.g., for authors)
                if isinstance(value, list):
                     display(Markdown(f"  - **{entity}:** {', '.join(map(str, value)) if value else 'None'}")) # Handle non-string list items
                else:
                     display(Markdown(f"  - **{entity}:** {value}"))
        display(Markdown("---")) # Add a separator between file results

Using Gemini model: gemini-2.0-flash-001
Listing PDFs in gs://tlab-extractionbucket3/papers3...
Found 129 PDF files.

Starting entity extraction for 129 PDF files using URIs...

--- Processing file 1/129: gs://tlab-extractionbucket3/papers3/S023_Frequent Mismatch Repair Protein Deficiency in Mixed Endometrioid and Clear Cell Carcinoma of the Endometrium.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S023_Frequent Mismatch Repair Protein Deficiency in Mixed Endometrioid and Clear Cell Carcinoma of the Endometrium.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S023_Frequent Mismatch Repair Protein Deficiency in Mixed Endometrioid and Clear Cell Carcinoma of the Endometrium.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S023_Frequent Mismatch Repair Protein Deficiency in Mixed Endometrioid and Clear Cell Carcinoma of the Endometrium.pdf.

--- Processing file 2/129: gs://tlab-extractionbucket3/papers3/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf.

--- Processing file 3/129: gs://tlab-extractionbucket3/papers3/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf.

--- Processing file 4/129: gs://tlab-extractionbucket3/papers3/S026_Association of p16 expression with prognosis varies across ovarian carcinoma histotypes- an Ovarian Tumor Tissue Analysis consortium study.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S026_Association of p16 expression with prognosis varies across ovarian carcinoma histotypes- an Ovarian Tumor Tissue Analysis consortium study.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S026_Association of p16 expression with prognosis varies across ovarian carcinoma histotypes- an Ovarian Tumor Tissue Analysis consortium study.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S026_Association of p16 expression with prognosis varies across ovarian carcinoma histotypes- an Ovarian Tumor Tissue Analysis consortium study.pdf.

--- Processing file 5/129: gs://tlab-extractionbucket3/papers3/S027_Sex Steroid Hormone Receptor Expression Affects Ovarian Cancer Survival.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S027_Sex Steroid Hormone Receptor Expression Affects Ovarian Cancer Survival.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S027_Sex Steroid Hormone Receptor Expression Affects Ovarian Cancer Survival.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S027_Sex Steroid Hormone Receptor Expression Affects Ovarian Cancer Survival.pdf.

--- Processing file 6/129: gs://tlab-extractionbucket3/papers3/S028_PIK3CA missense mutation is associated with unfavorable outcome in grade 3 endometrioid carcinoma but not in serous endometrial carcinoma.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S028_PIK3CA missense mutation is associated with unfavorable outcome in grade 3 endometrioid carcinoma but not in serous endometrial carcinoma.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S028_PIK3CA missense mutation is associated with unfavorable outcome in grade 3 endometrioid carcinoma but not in serous endometrial carcinoma.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S028_PIK3CA missense mutation is associated with unfavorable outcome in grade 3 endometrioid carcinoma but not in serous endometrial carcinoma.pdf.

--- Processing file 7/129: gs://tlab-extractionbucket3/papers3/S029_MMR deficiency is common in high-grade endometrioid carcinomas and is associated with an unfavorable outcome.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S029_MMR deficiency is common in high-grade endometrioid carcinomas and is associated with an unfavorable outcome.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S029_MMR deficiency is common in high-grade endometrioid carcinomas and is associated with an unfavorable outcome.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S029_MMR deficiency is common in high-grade endometrioid carcinomas and is associated with an unfavorable outcome.pdf.

--- Processing file 8/129: gs://tlab-extractionbucket3/papers3/S100_Functional analysis of p53 gene and the prognostic impact of dominant-negative p53 mutation in endometrial cancer.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S100_Functional analysis of p53 gene and the prognostic impact of dominant-negative p53 mutation in endometrial cancer.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S100_Functional analysis of p53 gene and the prognostic impact of dominant-negative p53 mutation in endometrial cancer.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S100_Functional analysis of p53 gene and the prognostic impact of dominant-negative p53 mutation in endometrial cancer.pdf.

--- Processing file 9/129: gs://tlab-extractionbucket3/papers3/S101_Identification of long non-coding RNAs biomarkers associated with progression of endometrial carcinoma and patient outcomes.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S101_Identification of long non-coding RNAs biomarkers associated with progression of endometrial carcinoma and patient outcomes.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S101_Identification of long non-coding RNAs biomarkers associated with progression of endometrial carcinoma and patient outcomes.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S101_Identification of long non-coding RNAs biomarkers associated with progression of endometrial carcinoma and patient outcomes.pdf.

--- Processing file 10/129: gs://tlab-extractionbucket3/papers3/S102_L1CAM is an independent predictor of poor survival in endometrial cancer - An analysis of The Cancer Genome Atlas (TCGA).pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S102_L1CAM is an independent predictor of poor survival in endometrial cancer - An analysis of The Cancer Genome Atlas (TCGA).pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S102_L1CAM is an independent predictor of poor survival in endometrial cancer - An analysis of The Cancer Genome Atlas (TCGA).pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S102_L1CAM is an independent predictor of poor survival in endometrial cancer - An analysis of The Cancer Genome Atlas (TCGA).pdf.

--- Processing file 11/129: gs://tlab-extractionbucket3/papers3/S103_Concomitant PI3K–AKT and p53 alterations in endometrial carcinomas are associated with poor prognosis.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S103_Concomitant PI3K–AKT and p53 alterations in endometrial carcinomas are associated with poor prognosis.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S103_Concomitant PI3K–AKT and p53 alterations in endometrial carcinomas are associated with poor prognosis.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S103_Concomitant PI3K–AKT and p53 alterations in endometrial carcinomas are associated with poor prognosis.pdf.

--- Processing file 12/129: gs://tlab-extractionbucket3/papers3/S104_Aromatase expression in stromal cells of endometrioid endometrial cancer correlates with poor survival.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S104_Aromatase expression in stromal cells of endometrioid endometrial cancer correlates with poor survival.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S104_Aromatase expression in stromal cells of endometrioid endometrial cancer correlates with poor survival.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S104_Aromatase expression in stromal cells of endometrioid endometrial cancer correlates with poor survival.pdf.

--- Processing file 13/129: gs://tlab-extractionbucket3/papers3/S105_Wilms Tumor Gene (WT1) and p53 expression in endometrial carcinomas- a study of 130 cases using a tissue microarray.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S105_Wilms Tumor Gene (WT1) and p53 expression in endometrial carcinomas- a study of 130 cases using a tissue microarray.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S105_Wilms Tumor Gene (WT1) and p53 expression in endometrial carcinomas- a study of 130 cases using a tissue microarray.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S105_Wilms Tumor Gene (WT1) and p53 expression in endometrial carcinomas- a study of 130 cases using a tissue microarray.pdf.

--- Processing file 14/129: gs://tlab-extractionbucket3/papers3/S106_PTEN expression is associated with prognosis for patients with advanced endometrial carcinoma undergoing postoperative chemotherapy.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S106_PTEN expression is associated with prognosis for patients with advanced endometrial carcinoma undergoing postoperative chemotherapy.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S106_PTEN expression is associated with prognosis for patients with advanced endometrial carcinoma undergoing postoperative chemotherapy.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S106_PTEN expression is associated with prognosis for patients with advanced endometrial carcinoma undergoing postoperative chemotherapy.pdf.

--- Processing file 15/129: gs://tlab-extractionbucket3/papers3/S107_High tumor tissue concentration of plasminogen activator inhibitor 2 (PAI-2) is an independent marker for shorter progression-free survival in patients with early stage endometrial cancer..pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S107_High tumor tissue concentration of plasminogen activator inhibitor 2 (PAI-2) is an independent marker for shorter progression-free survival in patients with early stage endometrial cancer..pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S107_High tumor tissue concentration of plasminogen activator inhibitor 2 (PAI-2) is an independent marker for shorter progression-free survival in patients with early stage endometrial cancer..pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S107_High tumor tissue concentration of plasminogen activator inhibitor 2 (PAI-2) is an independent marker for shorter progression-free survival in patients with early stage endometrial cancer..pdf.

--- Processing file 16/129: gs://tlab-extractionbucket3/papers3/S108_PTEN mutation located only outside exons 5, 6, and 7 is an independent predictor of favorable survival in endometrial carcinomas.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S108_PTEN mutation located only outside exons 5, 6, and 7 is an independent predictor of favorable survival in endometrial carcinomas.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S108_PTEN mutation located only outside exons 5, 6, and 7 is an independent predictor of favorable survival in endometrial carcinomas.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S108_PTEN mutation located only outside exons 5, 6, and 7 is an independent predictor of favorable survival in endometrial carcinomas.pdf.

--- Processing file 17/129: gs://tlab-extractionbucket3/papers3/S109_Prognostic significance of Notch signalling molecules and their involvement in the invasiveness of endometrial carcinoma cells.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S109_Prognostic significance of Notch signalling molecules and their involvement in the invasiveness of endometrial carcinoma cells.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S109_Prognostic significance of Notch signalling molecules and their involvement in the invasiveness of endometrial carcinoma cells.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S109_Prognostic significance of Notch signalling molecules and their involvement in the invasiveness of endometrial carcinoma cells.pdf.

--- Processing file 18/129: gs://tlab-extractionbucket3/papers3/S110_Genome-wide single-nucleotide polymorphism arrays in endometrial carcinomas associate extensive chromosomal instability with poor prognosis and unveil frequent chromosomal imbalances involved in the PI3.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S110_Genome-wide single-nucleotide polymorphism arrays in endometrial carcinomas associate extensive chromosomal instability with poor prognosis and unveil frequent chromosomal imbalances involved in the PI3.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S110_Genome-wide single-nucleotide polymorphism arrays in endometrial carcinomas associate extensive chromosomal instability with poor prognosis and unveil frequent chromosomal imbalances involved in the PI3.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S110_Genome-wide single-nucleotide polymorphism arrays in endometrial carcinomas associate extensive chromosomal instability with poor prognosis and unveil frequent chromosomal imbalances involved in the PI3.pdf.

--- Processing file 19/129: gs://tlab-extractionbucket3/papers3/S111_Comprehensive miRNA profiling of surgically staged endometrial cancer.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S111_Comprehensive miRNA profiling of surgically staged endometrial cancer.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S111_Comprehensive miRNA profiling of surgically staged endometrial cancer.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S111_Comprehensive miRNA profiling of surgically staged endometrial cancer.pdf.

--- Processing file 20/129: gs://tlab-extractionbucket3/papers3/S112_Angiogenic co-operation of VEGF and stromal cell TP in endometrial carcinomas.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S112_Angiogenic co-operation of VEGF and stromal cell TP in endometrial carcinomas.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S112_Angiogenic co-operation of VEGF and stromal cell TP in endometrial carcinomas.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S112_Angiogenic co-operation of VEGF and stromal cell TP in endometrial carcinomas.pdf.

--- Processing file 21/129: gs://tlab-extractionbucket3/papers3/S113_SLUG expression is an indicator of tumour recurrence in high-grade endometrial carcinomas.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S113_SLUG expression is an indicator of tumour recurrence in high-grade endometrial carcinomas.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S113_SLUG expression is an indicator of tumour recurrence in high-grade endometrial carcinomas.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S113_SLUG expression is an indicator of tumour recurrence in high-grade endometrial carcinomas.pdf.

--- Processing file 22/129: gs://tlab-extractionbucket3/papers3/S114_CyclinD1, a prominent prognostic marker for endometrial diseases.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket3/papers3/S114_CyclinD1, a prominent prognostic marker for endometrial diseases.pdf
  Calling Gemini API for gs://tlab-extractionbucket3/papers3/S114_CyclinD1, a prominent prognostic marker for endometrial diseases.pdf...
  Processing entity: % of participants with clinicopathological features (Stage I or II)
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket3/papers3/S114_CyclinD1, a prominent prognostic marker for endometrial diseases.pdf.

--- Processing file 23/129: gs://tlab-extractionbucket3/papers3/S115_Tetraspanin CD151 is a novel prognostic marker in poor outcome endometrial cancer.pdf ---

**File:** `gs://tlab-extractionbucket3/papers3/S023_Frequent Mismatch Repair Protein Deficiency in Mixed Endometrioid and Clear Cell Carcinoma of the Endometrium.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '68%', 'confidence': ['95', 'The text states that 53% of the tumors were in FIGO stage I and 15% of tumors were in FIGO stage II. Adding these values results in 68%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The paper focuses on high-risk endometrial cancers which suggests the study participants had a more advanced stage.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '92%', 'confidence': ['90', 'The paper states "Women with POLE-mutated endometrial carcinomas were younger, with stage I (92%) tumors", Stage II tumors are also included for the calculation.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S026_Association of p16 expression with prognosis varies across ovarian carcinoma histotypes- an Ovarian Tumor Tissue Analysis consortium study.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The paper does not specify the exact percentage of participants with Stage I or Stage II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S027_Sex Steroid Hormone Receptor Expression Affects Ovarian Cancer Survival.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '13%', 'confidence': ['100', 'This information was extracted from Table 1: Clinical Characteristics of Patients Included in the Study and Stratified for Hormone Receptor Expression Status in the Stage I row, indicating 13% of patients in this study had disease stage I or II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S028_PIK3CA missense mutation is associated with unfavorable outcome in grade 3 endometrioid carcinoma but not in serous endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The study does not directly specify the percentage of participants with Stage I or Stage II tumors. Although FIGO stage information is provided, it is for Stage III and IV only. Therefore, the exact percentage for Stage I or II cannot be accurately derived from the provided text.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S029_MMR deficiency is common in high-grade endometrioid carcinomas and is associated with an unfavorable outcome.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'I could not find the requested entity in the document.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S100_Functional analysis of p53 gene and the prognostic impact of dominant-negative p53 mutation in endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '65%', 'confidence': ['100', 'I am very confident that the information is correct, because the research paper directly states that 65% of the participants had Stage I or II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S101_Identification of long non-coding RNAs biomarkers associated with progression of endometrial carcinoma and patient outcomes.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '74.2%', 'confidence': ['99', 'The passage states that there were 223 early-stage patients (207 stage I and 16 stage II) out of the 300 UCEC patients. Taking 223/300 we derive 74.2%']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S102_L1CAM is an independent predictor of poor survival in endometrial cancer - An analysis of The Cancer Genome Atlas (TCGA).pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '72%', 'confidence': ['100', "The article states, 'Stage I, II, III, and IV comprised 62%, 10%, 23%, and 5%, respectively' which means that 72% of the tumors were at Stage I or II."]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S103_Concomitant PI3K–AKT and p53 alterations in endometrial carcinomas are associated with poor prognosis.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '79%', 'confidence': ['95', 'This is based on the numbers reported in the text. "Most tumors were FIGO stage I (89; 67%), 16 (12%) stage II". Thus, stage I and II add up to 79%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S104_Aromatase expression in stromal cells of endometrioid endometrial cancer correlates with poor survival.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '85%', 'confidence': ['95', 'The paper states that there were 40 patients with stage I disease and 7 patients with stage II disease, for a total of 47 out of 55 study participants, or 85%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S105_Wilms Tumor Gene (WT1) and p53 expression in endometrial carcinomas- a study of 130 cases using a tissue microarray.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', "The paper does not specify the percentage of participants with Stage I or Stage II clinicopathological features, so I can't extract the information."]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S106_PTEN expression is associated with prognosis for patients with advanced endometrial carcinoma undergoing postoperative chemotherapy.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The article discusses advanced endometrial carcinoma and does not mention the percentage of participants with Stage I or Stage II disease.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S107_High tumor tissue concentration of plasminogen activator inhibitor 2 (PAI-2) is an independent marker for shorter progression-free survival in patients with early stage endometrial cancer..pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '93%', 'confidence': ['100', 'The OCR extracted the sentence where the total number of patients with stage I or II disease was noted (254 patients of 274 which is 93%)']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S108_PTEN mutation located only outside exons 5, 6, and 7 is an independent predictor of favorable survival in endometrial carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '57%', 'confidence': ['95', 'The paper stated that 30/67 patients had stage I and 8/67 patients had stage II tumors, totaling 38/67, which equals 57%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S109_Prognostic significance of Notch signalling molecules and their involvement in the invasiveness of endometrial carcinoma cells.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The paper does not explicitly mention the percentage of participants with Stage I or Stage II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S110_Genome-wide single-nucleotide polymorphism arrays in endometrial carcinomas associate extensive chromosomal instability with poor prognosis and unveil frequent chromosomal imbalances involved in the PI3.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The study does not specifically mention the percentage of participants with Stage I or II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S111_Comprehensive miRNA profiling of surgically staged endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'This information is not available in the research paper.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S112_Angiogenic co-operation of VEGF and stromal cell TP in endometrial carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'I did not find the requested information in the text.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S113_SLUG expression is an indicator of tumour recurrence in high-grade endometrial carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '61.5%', 'confidence': ['100', 'Calculated from the text Stage I/II (n = 32) out of All cases (n = 52). 32/52=0.61538461538*100=61.5%']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S114_CyclinD1, a prominent prognostic marker for endometrial diseases.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', "The paper doesn't mention the percentage of patients in stage I or stage II."]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S115_Tetraspanin CD151 is a novel prognostic marker in poor outcome endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '58.8%', 'confidence': ['95', 'This number appears clearly in table 2 under the column CD151 and row (I-II) ']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S116_TP53 Mutational Spectrum in Endometrioid and Serous Endometrial Cancers.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The paper does not explicitly mention the percentage of study participants with disease Stage I or Stage II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S117_Clinical significance of pmTOR expression in endometrioid endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '69.3%', 'confidence': ['100', 'The text states that 43 out of 62 patients had stage I/II disease, 43/62 = 69.3%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S118_Inhibin-alpha subunit is an independent prognostic parameter in human endometrial carcinomas- analysis of inhibin activin-alpha, -betaA and -betaB subunits in 302 cases.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '74.5%', 'confidence': ['100', 'The value is explicitly stated in the main body of the paper.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S119_HER-2 neu expression is associated with high tumor cell proliferation and aggressive phenotype in a population based patient series of endometrial carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '80%', 'confidence': ['90', 'The extracted value 80% is present in the table 1 which contain the percentage of patients with clinicopathological features (Stage I or II) among the participants.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S120_Low BMI-1 expression is associated with an activated BMI-1-driven signature, vascular invasion, and hormone receptor loss in endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '56%', 'confidence': ['100', "The text clearly mentions 'I/II 118 (56%)' indicating 56% of the participants are with Stage I or Stage II tumors."]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S121_Loss of p63 and cytokeratin 5-6 expression is associated with more aggressive tumors in endometrial carcinoma patients.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '70%', 'confidence': ['100', 'The value is explicitly stated in Table 1 of the text: I/II 154 (70).']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S122_The prognostic value of PTEN, p53, and beta-catenin in endometrial carcinoma- a prospective immunocytochemical study.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '72.5%', 'confidence': ['100', 'The text explicitly states that 52.5% of participants were stage I and 20% were stage II, totaling 72.5%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S123_Overexpression of Lysine-Specific Demethylase 1 Is Associated With Tumor Progression and Unfavorable Prognosis in Chinese Patients With Endometrioid Endometrial Adenocarcinoma (1).pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'I apologize. This information is not explicitly mentioned in this paper. Therefore, I cannot provide a percentage.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S124_LRG1 is an independent prognostic factor for endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '86% in the test cohort and 90.7% in the validation cohort', 'confidence': ['95', 'The paper explicitly states the percentage of study participants with disease Stage I or Stage II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S125_Visfatin, a potential biomarker and prognostic factor for endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '80.70%', 'confidence': ['100', 'The exact percentage is stated in the 7th row of the FIGO stage section in Table 1.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S126_Promoter hypomethylation of EpCAM-regulated bone morphogenetic protein gene family in recurrent endometrial cancer..pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'I could not find the requested entity in the paper provided.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S127_Prognostic significance of miR-205 in endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '62%', 'confidence': ['90', 'The text states "Of these patients, 26 cases had stage I (54%), four cases had stage II (8%)". 54% + 8% = 62% (26+4)/48 = 62.5%, hence 62%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S128_Synuclein-γ (SNCG) protein expression is associated with poor outcome in endometrial adenocarcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '65% (Stage I) + 13% (Stage II) = 78%', 'confidence': ['100', 'The values for stage I and Stage II are explicitly stated in Table 1.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S129_DICER1 expression and outcomes in endometrioid endometrial adenocarcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '62.1%', 'confidence': ['95', 'The sum of the percentage of Stage I and Stage II tumors (47.9+14.2) from the table on page 12.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S130_Prognostic evaluation of epidermal fatty acid-binding protein and calcyphosine, two proteins implicated in endometrial cancer using a proteomic approach.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The paper does not contain any statement providing the percentage of study participants with clinicopathological features (Stage I or II).']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S131_Prognostic significance of E-cadherin protein expression in pathological stage I-III endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '77.4%', 'confidence': ['100', 'The abstract indicates that 102 patients with disease Stage I-III endometrial cancer were selected for the study, and the first line in the results section indicates that the majority of the patients were with pathological stage I disease (77.4%).']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S132_Changes in microRNA expression levels correlate with clinicopathological features and prognoses in endometrial serous adenocarcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '90.5%', 'confidence': ['95', 'The sum of patients at Stage I and Stage II is 19 out of 21, and the calculation leads to 90.5%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S133_The long non-coding RNA HOTAIR is upregulated in endometrial carcinoma and correlates with poor prognosis.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '68.9%', 'confidence': ['100', 'The value is directly extracted from Table II in the text, which presents the correlation between HOTAIR expression and clinicopathological parameters, indicating a high confidence in the extraction accuracy.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S134_Trefoil factor family 3 (TFF3) expression and its interaction with estrogen receptor (ER) in endometrial adenocarcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '71%', 'confidence': ['95', '62% with Stage I and 9% with Stage II for Type I endometrial tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S135_Role of emmprin in endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '63% of patients', 'confidence': ['90', 'The study included 134 patients, 74 in stage I and 11 in Stage II, so 85 participants with disease Stage I or Stage II tumors in this cohort of patients (63%).']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S136_YKL-40 protein levels and clinical outcome of human endometrial cancer..pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '80%', 'confidence': ['100', 'The text states that the majority of patients (70 - 80%) present with early-stage disease, implying that most participants presented with Stage I or II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S137_Altered expression of DACH1 and cyclin D1 in endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '62.7%', 'confidence': ['95', 'The percentage of participants with Stage I or II clinicopathological features (54.8% + 7.9%) was explicitly stated as such, leading to a high confidence score.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S138_Expression of Ret finger protein correlates with outcomes in endometrial cancer..pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '74.7%', 'confidence': ['95', '72 patients were stage I and 16 were stage II, so 88/119 = 73.9% but since values may be rounded in the text, I feel confident giving a 95% to stating 74.7%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S139_Proteomics identification of cyclophilin a as a potential prognostic factor and therapeutic target in endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '86.9%', 'confidence': ['95', 'The value was found on page 6 in the text in reference to surgical pathologic staging showing 40 were in stage I and eight were in stage II, for a total of 48, in a group of 52, which is 86.9%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S140_Prognostic impact of alterations in P-cadherin expression and related cell adhesion markers in endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'There is no explicit mention of percentage of study participants with disease Stage I or Stage II tumors in the paper.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S141_Loss of nuclear p16 protein expression is not associated with promoter methylation but defines a subgroup of aggressive endometrial carcinomas with poor prognosis.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'This information is not explicitly stated in the text.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S142_Significance of CD 105 expression for tumour angiogenesis and prognosis in endometrial carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The percentage of study participants with disease Stage I or Stage II tumors could not be found in this research paper.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S143_L1CAM expression associates with poor outcome in endometrioid, but not in clear cell ovarian carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '63%', 'confidence': ['95', 'Based on the statement, L1CAM-positivity was found in 7% of stage I-II and 28% of stage III-IV endometrioid ovarian carcinoma patients. The text said 63% were stage I or stage II.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S144_Expression of protease-activated receptor-2 (PAR-2) is related to advanced clinical stage and adverse prognosis in ovarian clear cell carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '74.7%', 'confidence': ['95', 'The paper states 71 out of 95 cases presented with disease stage I or Stage II tumors, meaning that the percentage of study participants with disease stage I or Stage II tumors is 74.7%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S145_Immunohistochemical Profiling of Endometrial Serous Carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'I am unable to locate the requested information in the research paper.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S146_Significant frequency of MSH2-MSH6 abnormality in ovarian endometrioid carcinoma supports histotype-specific Lynch syndrome screening in ovarian carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '68%', 'confidence': ['95', 'The value was found in Table 3 as 17 out of 25 (68%) of dMMR patients with clinicopathological features in stage I/II disease.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S147_Overexpression of HER-2 neu is not a risk factor in ovarian clear cell adenocarcinoma (1).pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '65.9%', 'confidence': ['100', 'Extracted from table 1 by adding the % of patients with Stage I and Stage II tumors (57.8% + 7.8%).']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S148_Significantly decreased P27 expression in endometrial carcinoma compared to complexhyperplasia with atypia (correlation with p53 expression).pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '86.9%', 'confidence': ['95', 'The sum of Stage I (81.6%) and Stage II (5.3%) participant percentages are added together.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S149_Loss of PTEN expression is associated with metastatic disease in patients with endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '82%', 'confidence': ['95', 'The table provides the number and percentage of cases with clinicopathological features (Stage I or II).']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S150_Clinical significance of microsatellite instability in endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '87%', 'confidence': ['95', 'Calculated from Table 1 in the paper, 54/70 (77%) + 7/70 (10%) = 61/70 (87%) of MSI (+) tumors presented with Stage I or Stage II disease.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S30_Integrated genomic characterization of endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The paper does not mention the percentage of study participants with disease Stage I or Stage II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S31_ARID1A mutations in endometriosis-associated ovarian carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The article is focused on mutations and does not contain the requested entity.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S32_Necrosis related HIF-1alpha expression predicts prognosis in patients with endometrioid endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '81%', 'confidence': ['100', 'This value was directly calculated from the values in Table 1 (58% Stage I and 23% Stage II), so the confidence is very high.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S33_Low membranous expression of b-catenin and high mitotic count predict poor prognosis in endometrioid carcinoma of the ovary.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '73%', 'confidence': ['80', 'From the paper, in Results Section: Further analysis showed that patients with stage III or IV disease had an approximately 5.3 times higher risk of death than patients with stage I or II carcinoma.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S34_Expression of estrogen receptor-alpha and -beta and progesterone receptor-A and -Bin a large cohort of patients with endometrioid endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '76.1%', 'confidence': ['95', 'The study indicated that 59.0% were in Stage I and 17.1% were in Stage II with a total of 76.1%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S35_Cyr61, a member of ccn (connective tissue growth factor cysteine-rich61 nephroblastoma overexpressed) family, predicts survival of patientswith endometrial cancer of endometrioid subtype.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'I am unable to find the number of patients with Stage I or Stage II tumors in the document.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S36_Promoter methylation of IGFBP-3 and p53 expression in ovarian endometrioid carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'I could not find the requested information in the paper.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S37_Cathepsin B protein levels in endometrial cancer- Potential value as a tumour biomarker.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '72.1%', 'confidence': ['90', 'This value was located directly in the table on the extracted page.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S38_Inverse correlation between tumoral indoleamine 2,3-dioxygenase expression and tumor-infiltrating lymphocytes in endometrial cancer- its association with disease progression and survival.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '76.9%', 'confidence': ['100', 'The text in the research paper explicitly states that 50 out of 65 patients were in stage I or II tumors, which is a percentage of 76.9%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S39_Expression of class I histone deacetylases indicates poor prognosis in endometrioid subtypes of ovarian and endometrial carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '97%', 'confidence': ['100', 'The text states "Approximately 97% of ovarian carcinoma patients were treated according to the provincial treatment guidelines of the British Columbia Cancer Agency"']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S40_Claudin-3 and claudin-4 expression in serous papillary, clear-cell, and endometrioid endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '97%', 'confidence': ['100', "The text 'Of the 287 patients included in this study, 279 patients (97%) had archived paraffin embedded tissue available for analysis of claudin-3 and claudin-4 expression' provides the percentage of patients with available clinicopathological features to analyze. There is no disease stage mentioned, however."]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S41_GATA3 expression in estrogen receptor alpha-negative endometrial carcinomas identifies aggressive tumors with high proliferation and poor patient survival.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '81%', 'confidence': ['100', "The value is explicitly mentioned in Table 1 in the row corresponding to 'FIGO stage' and the 'Stage I/II' category for the GATA3 negative participants."]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S42_Expression of epithelial membrane protein-2 is associated with endometrial adenocarcinoma of unfavorable outcome.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '57%', 'confidence': ['95', 'The majority of tumors (57%) were Stages IB to IIB.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S43_Progesterone receptor isoforms as a prognostic marker in human endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '75.7%', 'confidence': ['100', "The text states 'Stage I, II 78 (75.7%)' directly in the Table 1."]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S44_Clinical and pathological associations of PTEN expression in ovarian cancer- a multicentre study from the Ovarian Tumour Tissue Analysis Consortium.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '24%', 'confidence': ['100', 'The text reports that 24% of the cases belong to stage I or stage II.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S45_p53 mutations and overexpression affect prognosis of ovarian endometrioid cancer but not clear cell cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '52.9 %', 'confidence': ['95', "The value could be directly found in the main text on p.7: 'In contrast, we detected p53 mutation in 52.9 % of stage I/II ECs and 80.0 % of stage III/IV ECs.'"]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S46_Characterization of ovarian clear cell carcinoma using target drug-based molecular biomarkers- implications for personalized cancer therapy.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '66.7%', 'confidence': ['99', 'The text clearly states that early stage (I + II) participants make up 66.7% of the total participants.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S47_CD103 defines intraepithelial CD8+ PD1+ tumour-infiltrating lymphocytes of prognostic significance in endometrial adenocarcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '51.8% of patients with Stage I, and 17.4% with Stage II (total 69.2%)', 'confidence': ['95', 'The data for percentage of stage 1 and stage 2 patients can be explicitly found in Table 1 of the article.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S48_Prognostic significance of L1CAM expression and its association with mutant p53 expression in high-risk endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '54.3%', 'confidence': ['95', 'Based on Table 1, 36.2% of participants had Stage I and 18.1% had Stage II disease, adding up to 54.3%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S49_L1CAM Expression is Related to Non-Endometrioid Histology, and Prognostic for Poor Outcome in Endometrioid Endometrial Carcinoma..pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '81.6%', 'confidence': ['95', 'The text states that "Low (I-II)  84 (81.6%)", so the percentage of study participants with disease Stage I or Stage II tumors is 81.6%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S50_Silencing of UCA1, a poor prognostic factor, inhibited the migration of endometrial cancer cell.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '73.33%', 'confidence': ['95', 'This information was retrieved directly from the text. The text clearly states that 33 out of the 45 participants (73.33%) were stage I-II.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S51_DNA mismatch repair-related protein loss as a prognostic factor in endometrial cancers.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The research paper focuses on MMR proteins and endometrial cancer, but it does not contain any information about the percentage of study participants with Stage I or Stage II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S52_Expression and clinical significance of annexin A2 and human epididymis protein 4 in endometrial carcinoma (1).pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'This information is not mentioned in the research paper. The FIGO stage for all participants were not available.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S53_ARID1A loss correlates with mismatch repair deficiency and intact p53 expression in high-grade endometrial carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '63%', 'confidence': ['95', 'This value was extracted directly from the text on page 11. The total value matches Table 1.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S54_L1 cell adhesion molecule is a strong predictor for distant recurrence and overall survival in early stage endometrial cancer- pooled PORTEC trial results.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '97.7%', 'confidence': ['100', "The information is explicitly stated in Table 1 on page 3, under the 'Tumor Type' section."]}

---

**File:** `gs://tlab-extractionbucket3/papers3/S55_Evidence for a time-dependent association between FOLR1 expression and survival from ovarian carcinoma- implications for clinical testing. An Ovarian Tumour Tissue Analysis consortium study..pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'Among these patients, FOLR1 expression was associated with a 56% significant increased OS during the first 2 years of follow-up only (HR: 0.44, 95% CI: 0.20- 0.96, P=0.04).', 'confidence': ['90', 'The sentence mentions patients with disease stage I or II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S56_PIK3CA overexpression is a possible prognostic factor for favorable survival in ovarian clear cell carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '73%', 'confidence': ['95', 'Table 3 shows tumors overexpressing PIK3CA tended to include more Stage I disease, which would infer a higher percentage of total Stage I/II tumors among the participants.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S57_Immunoexpression of B7-H3 in endometrial cancer- relation to tumor T-cell infiltration and prognosis.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The paper provides tumor stage information, but does not state a combined percentage of Stage I and Stage II tumors.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S58_The autophagy protein LC3A correlates with hypoxia and is a prognostic marker of patient survival in clear cell ovarian cancer..pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The PDF does not explicitly mention this percentage, though it contains the number of cases for each stage (I, II and III) which can be used to estimate the percentage.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S59_Stathmin overexpression identifies high-risk patients and lymph node metastasis in endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '72.9%', 'confidence': ['100', 'The value is explicitly mentioned in Table 1 (FIGO Stage I).']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S60_IGF2BP3 (IMP3) expression is a marker of unfavorable prognosis in ovarian carcinoma of clear cell subtype.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '80%', 'confidence': ['90', 'The text mentions that clear cell carcinoma is mostly (80%) diagnosed at stage I or II.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S61_EphA2 overexpression is associated with lack of hormone receptor expression and poor outcome in endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '78%', 'confidence': ['100', 'The value 78% appears explicitly in the text.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S62_Aromatase, cyclooxygenase 2, HER-2 neu, and p53 as prognostic factors in endometrioid endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '76.1%', 'confidence': ['100', 'The sum of Stage I (59.0%) and Stage II (17.1%) totals 76.1% and is explicitly stated in the abstract.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S63_Expression of matriptase and clinical outcome of human endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '93.8', 'confidence': ['99', 'This value appears in Table II in the FIGO stage I+II row under the Estimated 5-year DFS (%) column.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S64_Ovarian carcinoma subtypes are different diseases- implications for biomarker studies.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '83.2%', 'confidence': ['100', 'The value can be derived by summing the percentage of participants with Stage I and Stage II tumors from Table 1, i.e. 41.0% + 42.2% = 83.2%']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S65_Prostate-specific membrane antigen expression is a potential prognostic marker in endometrial adenocarcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '64%', 'confidence': ['80', 'From Table 1 on page 2, the percentage of participants in Stage I is 64%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S66_GPR30- a novel indicator of poor survival for endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '63.8%', 'confidence': ['100', 'The value is explicitly stated in the paper in the first line under Table 2.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S67_Activation of ERK1-2 occurs independently of KRAS or BRAF status in endometrial cancer and is associated with favorable prognosis.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '82.5%', 'confidence': ['95', 'The text mentions that 46 tumors were classified as stage I and 6 tumors were classified as stage II, thus 52/63 or 82.5%.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S68_HER-2 is an independent prognostic factor in endometrial cancer- association with outcome in a large cohort of surgically staged patients.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '60%', 'confidence': ['100', 'The number was directly extracted from Table 1']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S69_Ezrin expression is related to poor prognosis in FIGO stage I endometrioid carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The percentage of study participants with disease Stage I or Stage II tumors could not be found in the research paper.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S70_Replicative MCM7 protein as a proliferation marker in endometrial carcinoma- a tissue microarray and clinicopathological analysis.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': '90.5%', 'confidence': ['90', '152 out of 168 cases presented with early-stage (Stage I or II) of endometrial carcinoma.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S71_Intratumoral CD8+ T lymphocytes as a prognostic factor of survival in endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'The paper does not explicitly state the percentage of participants with stage I or II tumors, but the table provides the number of patients in each stage.']}

---

**File:** `gs://tlab-extractionbucket3/papers3/S72_L1 expression as a predictor of progression and survival in patients with uterine and ovarian carcinomas.pdf`

  - **Status:** <font color='green'>Success</font>

  - **% of participants with clinicopathological features (Stage I or II):** {'value': 'n/a', 'confidence': ['0', 'This information is not present in this research paper.']}

---

In [ ]:
# @title ## User Search Integration

def search_extracted_papers(keyword_query, results):
    """Search the extracted entity results for user-specified keyword query.

    Args:
        keyword_query (str): User input in format "Entity: value"
        results (list): The list of extraction result dictionaries (e.g., all_results)

    Returns:
        list: List of matching PDF URIs and their matched entity value.
    """
    import re

    match = re.match(r"^\s*(.+?)\s*:\s*(.+?)\s*$", keyword_query)
    if not match:
        print("Invalid format. Use: Entity: value")
        return []

    entity, value = match.groups()
    entity = entity.strip()
    value = value.strip().lower()

    if not entity or not value:
        print("Invalid input. Provide both an entity and a value.")
        return []

    matches = []
    for result in results:
        entity_data = result.get(entity)
        if not entity_data or isinstance(entity_data, str) and entity_data == "n/a":
            continue

        # entity_data can be a dictionary with 'value' and 'confidence'
        extracted_value = entity_data.get("value") if isinstance(entity_data, dict) else entity_data
        if isinstance(extracted_value, list):
            extracted_value_str = ", ".join(map(str, extracted_value)).lower()
        else:
            extracted_value_str = str(extracted_value).lower()

        if value in extracted_value_str:
            matches.append({
                "pdf_uri": result.get("pdf_uri"),
                "matched_value": extracted_value
            })

    if not matches:
        print("No matches found.")
    else:
        print(f"Found {len(matches)} match(es):")
        for m in matches:
            print(f"- {m['pdf_uri']} → Matched: {m['matched_value']}")

    return matches

In [ ]:
# Example 1: Search for papers that analyzed POLE as a biomarker
search_extracted_papers("Analysed Biomarkers: POLE", all_results)

# Example 2: Search for studies with 192 patients
search_extracted_papers("N of total cohort: 192", all_results)

# Example 3: Search for endometrial studies
search_extracted_papers("Histology: Ovarian", all_results)

No matches found.
No matches found.
Found 3 match(es):
- gs://tlab-extractionbucket/papers/S001_Abundance of mitochondrial superoxide dismutase is a negative predictive biomarker for endometrioisis-associated ovarian cancers.pdf → Matched: Ovarian
- gs://tlab-extractionbucket/papers/S002_ADP-ribosylation-factor-like-4C-EAOC.pdf → Matched: Ovarian
- gs://tlab-extractionbucket/papers/S003_Nuclear β-catenin and CDX2 expression in ovarian endometrioid carcinoma identify patients with favourable outcome.pdf → Matched: Ovarian

[{'pdf_uri': 'gs://tlab-extractionbucket/papers/S001_Abundance of mitochondrial superoxide dismutase is a negative predictive biomarker for endometrioisis-associated ovarian cancers.pdf',
  'matched_value': 'Ovarian'},
 {'pdf_uri': 'gs://tlab-extractionbucket/papers/S002_ADP-ribosylation-factor-like-4C-EAOC.pdf',
  'matched_value': 'Ovarian'},
 {'pdf_uri': 'gs://tlab-extractionbucket/papers/S003_Nuclear β-catenin and CDX2 expression in\xa0ovarian\xa0endometrioid\xa0carcinoma\xa0identify patients with favourable outcome.pdf',
  'matched_value': 'Ovarian'}]

In [ ]:
pip install PyPDF2

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 12.8 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1

In [ ]:
# ENTITIES_TO_EXTRACT = {
# "Title of Paper": "Extract the title of the paper, e.g., POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium",
# "Analysed Biomarkers":"Extract which biomarkers were analysed in the study, e.g., POLE, p53, MMR, L1CAM, BRCA1. Only extract the top 3 most significant biomarkers, often mentioned in the methods and/or abstract and/or conclusion and analysing the surrounding text if the biomarker is found in the abstract to make sure it is not mentioned as contextual information, and is actually being analyzed in the paper.",
#  "Biomarker combinations":"Based on the biomarkers studied in this paper, what combinations of biomarkers were analyzed together in the same context (e.g., same figure, table, or statistical model)?",
# "Survival analysis": (
#         "Check for univariable survival analyses done for each biomarker. "
#         "For each, specify what survival variable was tested (e.g., OS, PFS) and report the p-value. "
#         "Then, check whether a multivariable survival analysis was performed. If yes, state which biomarkers were included and their p-values. "
#         "Summarize key survival findings clearly."
#     ),
# "Confounding factors": "Were any confounding factors (e.g., age, stage, histotype) considered in the survival analysis involving biomarker combinations? Return 'Yes' or 'No'. Also, how many different combinations of biomarkers were analyzed together?",
# "Primary biomarker": "Identify the primary biomarker studied in this paper (i.e., the one most emphasized in title, abstract, or results). List additional biomarkers also studied and the total number of mentions or contexts for each (e.g., subgroup analysis, comparison).",
# "Key Findings": "Return the key overeall findings relating to the biomarkers from the paper. They are most likely mentioned in the Results section/"
# }

In [ ]:
# @title ## MEREDITH Extractor (S2 Test)

all_results = []
limit = 11

# Check prerequisites
if not client:
    print("ERROR: GenAI Client not initialized. Please fix configuration.")
elif not storage_client:
    print("ERROR: GCS client not initialized. Please fix configuration.")
else:
    # 1. List PDF files in GCS
  pdf_files_to_process = [
        "S008_S100A1 Expression in Ovarian and Endometrial Endometrioid Carcinomas Is a Prognostic Indicator of Relapse-Free Survival.pdf",
        "S011_POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium.pdf",
        "S015_Molecular classification defines outcomes and opportunities in young women with endometrial carcinoma.pdf",
        "S018_Molecular Classification of Grade 3 Endometrioid Endometrial Cancers Identifies Distinct Prognostic Subgroups.pdf",
        "S019_L1CAM further stratifies endometrial carcinoma patients with no specific molecular risk profile.pdf",
        "S021_Confirmation of ProMisE- A simple, genomics-based clinical classifier for endometrial cancer.pdf",
        "S022_Evaluation of endometrial carcinoma prognostic immunohistochemistry markers in the context of molecular classification.pdf",
        "S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf",
        "S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf",
        "S30_Integrated genomic characterization of endometrial carcinoma.pdf",
    ]

  pdf_uris = list_pdfs_in_gcs(storage_client, GCS_BUCKET_NAME, GCS_PREFIX)

  pdf_uris = [
        uri for uri in pdf_uris
        if any(uri.endswith(filename) for filename in pdf_files_to_process)
    ]

if not pdf_uris:
        print("\nNo PDF files found or error listing files. Ensure configuration is correct and files exist.")
else:
        print(f"\nStarting entity extraction for {len(pdf_uris)} PDF files using URIs...")

        # 2. Loop through each PDF URI
        for i, pdf_uri in enumerate(pdf_uris):
          if i > limit:
            break
          print(f"\n--- Processing file {i+1}/{len(pdf_uris)}: {pdf_uri} ---")
          file_result = {"pdf_uri": pdf_uri}

          # 3. Extract Entities using Gemini directly with the URI
          entities_data = extract_entities_with_gemini_uri(pdf_uri, ENTITIES_TO_EXTRACT)
          file_result.update(entities_data)



          if "error" in entities_data:
              print(f"Extraction failed for {pdf_uri}: {entities_data['error']}")
          else:
                print(f"Extraction successful for {pdf_uri}.")

          all_results.append(file_result)

          # Optional: Add a small delay to avoid hitting potential rate limits
          # time.sleep(1) # Sleep for 1 second between requests

        print("\n--- Processing Complete ---")


print(f"\n--- Extracted Information ({len(all_results)} files processed) ---")

# Check if any results were generated
if not all_results:
    print("No results were generated. Please check previous cell outputs for errors.")
else:
    # Iterate and display results for each file
    for result in all_results:
        display(Markdown(f"**File:** `{result.get('pdf_uri', 'N/A')}`")) # Get URI safely
        if "error" in result:
            # Display error message clearly
            display(Markdown(f"  - **Status:** <font color='red'>Error - {result['error']}</font>"))
            # Optionally display raw response snippet if available and useful
            if "raw_response" in result:
                 display(Markdown(f"  - **Raw Response Snippet:**"))
                 display(Markdown(f"```\n{textwrap.shorten(result['raw_response'], width=150, placeholder='...')}\n```"))
        else:
            # Display success and extracted entities
            display(Markdown(f"  - **Status:** <font color='green'>Success</font>"))
            for entity in ENTITIES_TO_EXTRACT:
                raw_entity = result.get(entity, "Not Found")

                if isinstance(raw_entity, dict):
                    value = raw_entity.get("value", "Not Found")
                    confidence = raw_entity.get("confidence", None)
                else:
                    value = raw_entity
                    confidence = None


                    # Format list display (e.g., for authors)
                if isinstance(value, list):
                    value_str = ', '.join(map(str, value)) if value else 'None'
                else:
                    value_str = str(value)

                confidence_str = f" _(Confidence: {confidence}%)_" if confidence is not None else ""

                display(Markdown(f"  - **{entity}:** {value_str}{confidence_str}"))

        display(Markdown("---")) # Add a separator between file results

Listing PDFs in gs://tlab-extractionbucket/papers...
Found 25 PDF files.

Starting entity extraction for 10 PDF files using URIs...

--- Processing file 1/10: gs://tlab-extractionbucket/papers/S008_S100A1 Expression in Ovarian and Endometrial Endometrioid Carcinomas Is a Prognostic Indicator of Relapse-Free Survival.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S008_S100A1 Expression in Ovarian and Endometrial Endometrioid Carcinomas Is a Prognostic Indicator of Relapse-Free Survival.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S008_S100A1 Expression in Ovarian and Endometrial Endometrioid Carcinomas Is a Prognostic Indicator of Relapse-Free Survival.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S008_S100A1 Expression in Ovarian and Endometrial Endometrioid Carcinomas Is a Prognostic Indicator of Relapse-Free Survival.pdf.

--- Processing file 2/10: gs://tlab-extractionbucket/papers/S011_POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S011_POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S011_POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S011_POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium.pdf.

--- Processing file 3/10: gs://tlab-extractionbucket/papers/S015_Molecular classification defines outcomes and opportunities in young women with endometrial carcinoma.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S015_Molecular classification defines outcomes and opportunities in young women with endometrial carcinoma.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S015_Molecular classification defines outcomes and opportunities in young women with endometrial carcinoma.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S015_Molecular classification defines outcomes and opportunities in young women with endometrial carcinoma.pdf.

--- Processing file 4/10: gs://tlab-extractionbucket/papers/S018_Molecular Classification of Grade 3 Endometrioid Endometrial Cancers Identifies Distinct Prognostic Subgroups.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S018_Molecular Classification of Grade 3 Endometrioid Endometrial Cancers Identifies Distinct Prognostic Subgroups.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S018_Molecular Classification of Grade 3 Endometrioid Endometrial Cancers Identifies Distinct Prognostic Subgroups.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S018_Molecular Classification of Grade 3 Endometrioid Endometrial Cancers Identifies Distinct Prognostic Subgroups.pdf.

--- Processing file 5/10: gs://tlab-extractionbucket/papers/S019_L1CAM further stratifies endometrial carcinoma patients with no specific molecular risk profile.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S019_L1CAM further stratifies endometrial carcinoma patients with no specific molecular risk profile.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S019_L1CAM further stratifies endometrial carcinoma patients with no specific molecular risk profile.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S019_L1CAM further stratifies endometrial carcinoma patients with no specific molecular risk profile.pdf.

--- Processing file 6/10: gs://tlab-extractionbucket/papers/S021_Confirmation of ProMisE- A simple, genomics-based clinical classifier for endometrial cancer.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S021_Confirmation of ProMisE- A simple, genomics-based clinical classifier for endometrial cancer.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S021_Confirmation of ProMisE- A simple, genomics-based clinical classifier for endometrial cancer.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S021_Confirmation of ProMisE- A simple, genomics-based clinical classifier for endometrial cancer.pdf.

--- Processing file 7/10: gs://tlab-extractionbucket/papers/S022_Evaluation of endometrial carcinoma prognostic immunohistochemistry markers in the context of molecular classification.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S022_Evaluation of endometrial carcinoma prognostic immunohistochemistry markers in the context of molecular classification.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S022_Evaluation of endometrial carcinoma prognostic immunohistochemistry markers in the context of molecular classification.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S022_Evaluation of endometrial carcinoma prognostic immunohistochemistry markers in the context of molecular classification.pdf.

--- Processing file 8/10: gs://tlab-extractionbucket/papers/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf.

--- Processing file 9/10: gs://tlab-extractionbucket/papers/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf.

--- Processing file 10/10: gs://tlab-extractionbucket/papers/S30_Integrated genomic characterization of endometrial carcinoma.pdf ---
  Preparing request for Gemini with URI: gs://tlab-extractionbucket/papers/S30_Integrated genomic characterization of endometrial carcinoma.pdf
  Calling Gemini API for gs://tlab-extractionbucket/papers/S30_Integrated genomic characterization of endometrial carcinoma.pdf...
  Processing entity: Title of Paper
  Received response from Gemini.
  Processing entity: Analysed Biomarkers
  Received response from Gemini.
  Processing entity: Biomarker combinations
  Received response from Gemini.
  Processing entity: Survival analysis
  Received response from Gemini.
  Processing entity: Confounding factors
  Received response from Gemini.
  Processing entity: Primary biomarker
  Received response from Gemini.
  Processing entity: Key Findings
  Received response from Gemini.
Extraction successful for gs://tlab-extractionbucket/papers/S30_Integrated genomic characterization of endometrial carcinoma.pdf.

--- Processing Complete ---

--- Extracted Information (10 files processed) ---

**File:** `gs://tlab-extractionbucket/papers/S008_S100A1 Expression in Ovarian and Endometrial Endometrioid Carcinomas Is a Prognostic Indicator of Relapse-Free Survival.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** S100A1 Expression in Ovarian and Endometrial Endometrioid Carcinomas Is a Prognostic Indicator of Relapse-Free Survival _(Confidence: ['100', 'The title is clearly visible at the beginning of the document.']%)_

  - **Analysed Biomarkers:** S100A1, CD3, HDAC1 _(Confidence: ['85', 'S100A1 is listed in the title and abstract, and CD3 and HDAC1 were found by using the same TMAs as the study. ']%)_

  - **Biomarker combinations:** S100A1 expression was analyzed in conjunction with CD3+ and CD8+ T cells to assess correlations, particularly in endometrioid ovarian cancer. Additionally, in endometrioid ovarian cancer, S100A1 staining was analyzed alongside HDAC1 expression to identify different subsets of patients with decreased relapse-free survival. _(Confidence: ['95', 'The text explicitly mentions the analysis of S100A1 in conjunction with T cell markers (CD3+ and CD8+) and HDAC1 in specific contexts, indicating that these biomarker combinations were specifically investigated.']%)_

  - **Survival analysis:** Univariable survival analyses using Kaplan-Meier survival curves were performed for relapse-free survival (RFS) for the entire cohort and for each histopathologic subtype, with significance tested using the Cox proportional hazards test (P < .05). In histologic subtype-specific relapse-free survival analysis, the S100A1-associated decrease in relapse-free survival time was found to exist only in the endometrioid subtype (P = .004).
Multivariable analysis of the endometrioid subtype of ovarian cancer by stage, grade, and S100A1 expression showed that only stage and S100A1 expression remained significant (Table 3), indicating that S100A1 expression is of independent prognostic significance. Specifically, the p-value for S100A1 expression in the multivariable analysis was .0131 _(Confidence: ['95', 'The relevant information was clearly stated in the text.']%)_

  - **Confounding factors:** Yes, stage, grade, and histotype were considered in the survival analysis. Only a single biomarker (S100A1) was analyzed. _(Confidence: ['100', 'The analysis explicitly mentions stage, grade, and histotype as well as S100A1.']%)_

  - **Primary biomarker:** S100A1 _(Confidence: ['100', "S100A1 is in the paper's title and is mentioned throughout the abstract and results sections. "]%)_

  - **Key Findings:** The data suggest that S100A1 is a marker for poor prognosis of endometrioid subtypes of cancer. Relapse-free survival was decreased for patients with S100A1+ tumors, particularly in the endometrioid subtype of ovarian and endometrial cancers. Expression of S100A1 also increased with increasing Silverberg grade in ovarian serous tumors but did not vary with stage in any histologic subtype. _(Confidence: ['90', 'These are the main findings reported in the abstract and results section of the paper relating to the biomarker and the study cohort.']%)_

---

**File:** `gs://tlab-extractionbucket/papers/S011_POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** POLE exonuclease domain mutation predicts long progression-free survival in grade 3 endometrioid carcinoma of the endometrium _(Confidence: ['100', 'The title is prominently displayed at the top of the first page of the research paper.']%)_

  - **Analysed Biomarkers:** POLE, MMR, PIK3CA _(Confidence: ['90', 'POLE is mentioned in the abstract, introduction, and conclusion of the paper, while MMR and PIK3CA are found in the results and discussion, making them relevant biomarkers analysed in the study.']%)_

  - **Biomarker combinations:** PIK3CA hotspot (exon 9 or 20) mutations were analyzed in conjunction with POLE exonuclease domain mutations.

MLH1, PMS2, MSH2 and MSH6 (mismatch repair proteins) and POLE exonuclease domain mutations were analyzed in combination. _(Confidence: ['100', 'Explicit statements of these biomarkers being analyzed together were found in the text.']%)_

  - **Survival analysis:** Univariable survival analyses were performed. Progression-free survival: POLE exonuclease domain mutation was associated with significantly better progression-free survival (p = 0.025). Overall survival: POLE exonuclease domain mutation was a significant prognostic factor for overall survival in EC3 (p = 0.046). Disease-specific survival for HGEC cohort: POLE exonuclease domain mutation showed a similar trend, though the difference was not statistically significant (p = 0.12). Multivariable survival analysis was performed. Progression-free survival: The presence of POLE exonuclease domain mutations remained a significant prognostic parameter for progression-free survival (p = 0.010) in multivariate analysis adjusted for age (p = 0.24) and FIGO stage (p < 0.0001). The key survival finding is that POLE exonuclease domain mutations in grade 3 endometrioid carcinomas are associated with better progression-free survival. _(Confidence: ['95', 'The information is explicitly stated in the paper.']%)_

  - **Confounding factors:** Yes, the multivariate analysis in the study, adjusted for age (as a continuous variable) and FIGO stage (stage I/II versus III/IV). Additionally, the study analyzed different combinations of biomarkers; specifically, POLE exonuclease domain mutation in conjunction with mismatch repair protein expression and PIK3CA hotspot mutations, which are 3 biomarkers analyzed in different combinations. _(Confidence: ['100', 'The text explicitly mentions that the multivariate analysis adjusted for age and FIGO stage. It also mentions the combinations of biomarkers analyzed.']%)_

  - **Primary biomarker:** POLE exonuclease domain mutation _(Confidence: ['99', 'This biomarker is emphasized in the title and abstract as well as the main topic of the study.']%)_

  - **Key Findings:** POLE exonuclease domain mutations were identified in 8 of 53 (15%) grade 3 endometrioid carcinomas and not in any other histotypes examined. When analyzed together with published grade 3 endometrioid carcinomas by The Cancer Genome Atlas, the presence of POLE exonuclease domain mutation was associated with significantly better progression-free survival in univariate (p = 0.025) and multivariate (p = 0.010) analyses, such that none of the patients with POLE mutated tumors experienced disease progression _(Confidence: ['95', 'These findings are directly extracted from the Results section of the research paper, specifically addressing the prevalence and prognostic impact of POLE mutations in grade 3 endometrioid carcinomas.']%)_

---

**File:** `gs://tlab-extractionbucket/papers/S015_Molecular classification defines outcomes and opportunities in young women with endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** Molecular classification defines outcomes and opportunities in young
women with endometrial carcinoma _(Confidence: ['100', 'The title is prominently displayed at the top of the first page.']%)_

  - **Analysed Biomarkers:** MMR, POLE, p53 _(Confidence: ['95', 'These biomarkers are explicitly mentioned in the abstract as being analysed in the study to determine ProMisE molecular subtypes. Therefore, it is reasonable to have a high confidence.']%)_

  - **Biomarker combinations:** The Proactive Molecular risk classifier for Endometrial Carcinoma (ProMisE) utilizes pragmatic molecular tests to identify ECs with:
1. Mismatch repair deficiency (MMRd),
2. Mutations in the exonuclease domain of DNA polymerase epsilon (POLE),
3. Wild type or aberrant p53 expression (p53wt, p53abn) _(Confidence: ['100', 'The information is explicitly stated in the abstract and introduction of the paper.']%)_

  - **Survival analysis:** The research paper does include survival analyses.

Univariable survival analysis was performed for the ProMisE molecular subtypes (MMRd, POLE, p53wt, and p53abn) and clinical risk groups ('High Estrogen', 'Lynch-like', 'Neither') for overall survival (OS), disease-specific survival (DSS), and progression-free survival (PFS).
Multivariable (MV) analysis was performed correcting for parameters that would be available from time of first diagnostic endometrial biopsy or curettage diagnosis to emulate future clinical application; age, BMI, histotype, grade, and ProMisE subtype were assessed. They also performed MV analysis encompassing additional parameters available post-staging, including stage and LVSI, and adjusted for treatment.

Key Survival Findings:
ProMisE subtypes were associated with overall survival (OS), and disease-specific survival (DSS) (log rank p < 0.001 for both).
Multivariable survival analysis demonstrated ProMisE molecular classification maintained an association with overall and disease-specific survival with p-values of 0.036, 0.02 respectively. _(Confidence: ['100', 'The extracted data can be found directly in the text, and both multivariable and univariable survival analyses are stated.']%)_

  - **Confounding factors:** Yes, the survival analysis considered potential confounding factors. The multivariable (MV) analysis corrected for parameters available from the time of first diagnostic biopsy/curettage to emulate future clinical application; age, BMI, histotype, grade, and ProMisE subtype were assessed. _(Confidence: ['100', 'The answer is explicitly stated in the text, so the confidence score is 100.']%)_

  - **Primary biomarker:** Proactive Molecular risk classifier for Endometrial Carcinoma (ProMisE) _(Confidence: ['100', 'The title states "Molecular classification defines outcomes and opportunities", and in the abstract the authors state "Our aim was to evaluate the prognostic significance of Proactive Molecular risk classifier for Endometrial Carcinoma (ProMisE) in young (<50 yo) women with EC."']%)_

  - **Key Findings:** ProMisE molecular classification is prognostic in young women with EC, enabling early stratification and risk assignment to direct care.  Further studies can assess response to therapy, fertility, and cancer-related outcomes within the framework of molecular subtype. _(Confidence: ['95', "This statement is directly taken from the paper's conclusion and summarizes the overall findings related to the biomarkers."]%)_

---

**File:** `gs://tlab-extractionbucket/papers/S018_Molecular Classification of Grade 3 Endometrioid Endometrial Cancers Identifies Distinct Prognostic Subgroups.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** Molecular classification of grade 3 endometrioid endometrial cancers identifies distinct prognostic subgroups _(Confidence: ['100', 'The title of the paper is at the beginning of the text and stands out from the rest of the text.']%)_

  - **Analysed Biomarkers:** POLE, MMR, p53 _(Confidence: ['95', 'These biomarkers are mentioned in the abstract, methods and conclusion of the paper, and are clearly used to classify EEC samples.']%)_

  - **Biomarker combinations:** The study analyzed the following combinations of biomarkers to classify grade 3 endometrioid endometrial carcinomas into distinct subgroups: p53 and MMR; p53 and POLE; MMR and POLE. _(Confidence: ['100', 'This confidence score is given because the classification tool and definitions of the molecular subgroups are mentioned explicitly in the Molecular subgroup assignment section, indicating these combinations were directly analyzed.']%)_

  - **Survival analysis:** Univariable Survival Analysis:

*   **OS:**
    *   POLE mutant vs. NSMP: HR 0.36, p=0.003
*   **RFS:**
    *   POLE mutant vs. NSMP: HR 0.17, p=0.003
    *   p53abn vs. NSMP: HR 1.73, p=0.021

Multivariable Survival Analysis:

The multivariable Cox model included age and FIGO stage.

*   **RFS**: POLE and MMRd status remained independent prognostic factors for better RFS, and p53 status was an independent prognostic factor for worse RFS.

Key Survival Findings:

*   Patients with POLE mutant grade 3 EEC had a significantly better prognosis.
*   Patients with p53abn tumors had a significantly worse RFS.
*   MMRd tumors showed a trend towards better RFS.
*   In Stage I only, multivariable analysis demonstrated that POLE mutant tumors had significantly longer RFS (p=0.05), and p53abn remained prognostically unfavorable compared to NSMP with respect to RFS (p=0.004). _(Confidence: ['95', 'The information is directly available in the text of the article with associated p-values.']%)_

  - **Confounding factors:** Yes, age and FIGO stage were considered as confounding factors in the multivariable Cox model for survival analysis. _(Confidence: ['100', 'The paper explicitly states that age and FIGO stage were included in the multivariable Cox model, and four different combinations of biomarkers subgroups were analyzed together: POLE, MMRd, p53abn and NSMP.']%)_

  - **Primary biomarker:** The primary biomarkers studied in this paper are a combination of:
        1.  POLE exonuclease domain mutations (POLE)
        2.  Mismatch repair deficiency (MMRd)
        3.  p53 abnormal (p53abn)
        4.  No specific molecular profile (NSMP) _(Confidence: ['100', 'These biomarkers were emphasized in the abstract, methods, results, and discussion sections. These four biomarkers were the core of their classification. The authors tested the hypothesis that the molecular subtypes of grade 3 EECs are associated with significant differences in prognosis, using a clinically applicable molecular classification tool.']%)_

  - **Key Findings:** In this group, stage remains an important prognostic factor with respect to both OS and RFS. POLE mutations are frequent, are associated with early stage disease, and arise in patients younger than those in other genomic subgroups. POLE mutant group assignment is independently associated with favorable OS and RFS, whereas p53abn is associated with a significantly worse prognosis. _(Confidence: ['100', 'This statement directly summarizes the key prognostic findings related to the molecular subgroups analyzed in the study, as it synthesizes information from the Discussion and Results sections.']%)_

---

**File:** `gs://tlab-extractionbucket/papers/S019_L1CAM further stratifies endometrial carcinoma patients with no specific molecular risk profile.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** L1CAM further stratifies endometrial carcinoma patients with no specific molecular risk profile _(Confidence: ['100', 'The title is located at the top of the first page and is clearly identifiable.']%)_

  - **Analysed Biomarkers:** POLE, MMR-D, L1CAM _(Confidence: ['90', 'The extracted biomarkers were found in the abstract and methods section of the paper, and were found to be analysed, and not just mentioned contextually.']%)_

  - **Biomarker combinations:** L1CAM with ProMisE subgroups (POLE, MMR-D, p53 wt/NSMP, and p53 abn).
L1CAM, age and ProMisE subgroups.
L1CAM with other immunohistochemical markers (unspecified).
L1CAM and clinicopathological risk factors (age, tumour grade, histology, LVSI and stage). _(Confidence: ['95', 'The combinations are explicitly mentioned in the statistical and survival analyses presented in tables and figures. The combinations of IHC and clinical features are supported by multiple instances.']%)_

  - **Survival analysis:** The research paper includes both univariable and multivariable survival analyses.

**Univariable Survival Analyses:**

*   L1CAM status in p53 wt/NSMP tumours was associated with OS (p = 0.002; HR 3.78) and DSS (p = 0.0008; HR 7.82).
*   Prognostic trends for L1CAM positivity and worse outcome were observed, but not statistically significant, in the other ProMisE subgroups (POLE, MMR-D, and p53 abn).

**Multivariable Survival Analyses:**

*   Analysis was performed with ProMisE subgroups, age, and L1CAM status. L1CAM status showed a trend for DSS (p = 0.05; HR 2.05), while ProMisE subgroups were significant for OS and DSS.

**p53 wt/NSMP Subgroup Analyses:**

*   In a multivariate model using preoperative biopsy or curettage samples (age, histotype, FIGO grade), L1CAM status was a strong and independent prognosticator for DSS (p = 0.035; HR 3.80).
*   In a multivariate model including factors from hysterectomy specimens (age, histotype, FIGO grade, FIGO stage, LVSI), L1CAM status remained prognostic for DSS (p = 0.035; HR 4.03).

**Key survival findings:** The key survival finding is that L1CAM expression is significantly associated with worse overall survival (OS) and disease-specific survival (DSS) in the p53 wt/NSMP subgroup of endometrial cancer patients. L1CAM was found to be an independent prognostic factor for DSS in multivariate analyses. _(Confidence: ['100', 'This is a direct summary of the survival analysis results reported within the research paper.']%)_

  - **Confounding factors:** Yes. The survival analysis involving biomarker combinations considered age as a confounding factor. Only one combination of biomarkers were analyzed together - L1CAM and ProMisE. _(Confidence: ['85', 'The multivariate analysis section mentions that age was included in the analysis. The research analyzes the prognostic significance of L1CAM in ProMisE subgroups, which implies that L1CAM and each ProMisE subgroup are analyzed in combination, but ProMisE is a surrogate marker and not a biomarker combination.']%)_

  - **Primary biomarker:** L1CAM _(Confidence: ['100', 'L1CAM is emphasized in the title, abstract, results and discussion of the paper.']%)_

  - **Key Findings:** L1CAM status was predictive of worse outcome among tumours with no specific molecular profile (p53 wt/NSMP) (p < 0.0001). Among p53 wt/NSMP EC, L1CAM remained a significant prognosticator for disease-specific survival after multivariate analysis (p = 0.035). _(Confidence: ['95%', 'The Key Finding is found almost verbatim within the results section.']%)_

---

**File:** `gs://tlab-extractionbucket/papers/S021_Confirmation of ProMisE- A simple, genomics-based clinical classifier for endometrial cancer.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** Confirmation of ProMisE: A Simple, Genomics-Based Clinical Classifier for Endometrial Cancer _(Confidence: ['100', 'The title is located at the top of the page, formatted distinctively, and is clearly identified as the title.']%)_

  - **Analysed Biomarkers:** MMR, POLE, p53 _(Confidence: ['100', 'These biomarkers are highlighted in the abstract and are shown to be the primary markers analysed to derive the ProMisE molecular classifier.']%)_

  - **Biomarker combinations:** The ProMisE classifier assigns endometrial cancer patients to one of four groups based on combinations of mismatch repair (MMR) protein status, sequencing for polymerase-c (POLE) exonuclease domain mutations (EDMs), and tumor protein 53 (p53) expression. _(Confidence: ['100', 'This information is explicitly stated in the BACKGROUND and INTRODUCTION sections of the paper.']%)_

  - **Survival analysis:** The study performed univariable and multivariable survival analyses. In univariable analyses, ProMisE subgroups were significantly associated with OS (p<0.0000), DSS (p<0.0000), and PFS (p<0.0000) (Table 3). In multivariable analysis using parameters available at diagnosis (age, BMI, grade, histology, treatment, and ProMisE subgroup), ProMisE subgroup was independently associated with OS (p=0.021), DSS (p=0.016), and PFS (p=0.001) (Table 4). When accounting for postsurgical staging parameters, the independent association of ProMisE with outcomes was not significant. _(Confidence: ['100', 'The information is directly stated in the text.']%)_

  - **Confounding factors:** Yes, age, BMI, grade, and histotype were corrected in addition to molecular subgroup as assigned by ProMisE. _(Confidence: ['90', 'The research paper mentions that Cox proportional-hazards model was considered with ProMisE subgroups and prognostic factors like age, BMI, grade, and histotype. However, the number of different biomarker combinations analyzed together is not available.']%)_

  - **Primary biomarker:** Proactive Molecular Risk Classifier for Endometrial Cancer (ProMisE) _(Confidence: ['95', "The title states 'Confirmation of ProMisE' and the abstract describes 'ProMisE, a molecular classification system'"]%)_

  - **Key Findings:** ProMisE decision-tree classification achieved categorization of all cases and identified 4 prognostic subgroups with distinct overall, disease-specific, and progression-free survival. Tumors with POLE EDMs had the most favorable prognosis, and those with p53 abn the worst prognosis, and separation of the 2 middle survival curves (p53 wt and MMR-D) was observed. There were no significant differences in survival between the ESMO low-risk and intermediate-risk groups. ProMisE improved the ability to discriminate outcomes compared with ESMO risk stratification. _(Confidence: ['100', 'This is directly stated in the results section and accurately summarizes the key findings.']%)_

---

**File:** `gs://tlab-extractionbucket/papers/S022_Evaluation of endometrial carcinoma prognostic immunohistochemistry markers in the context of molecular classification.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** Evaluation of endometrial carcinoma prognostic immunohistochemistry markers in the context of molecular classification _(Confidence: ['100', 'The title is clearly visible and identifiable at the beginning of the document.']%)_

  - **Analysed Biomarkers:** L1CAM, Progesterone Receptor (PR), Estrogen Receptor (ER) _(Confidence: ['100', 'These biomarkers are mentioned in the abstract and methods section, and are the main focus of the study.']%)_

  - **Biomarker combinations:** The paper analyzes combinations such as: L1CAM with ProMisE molecular subtypes, PR with ProMisE molecular subtypes, ER with ProMisE molecular subtypes, L1CAM, PR, and ER with clinicopathological parameters and stathmin (STMN) and phosphatase and tensin homolog (PTEN) assessing their value in the framework of modern molecular classification (by ProMisE). _(Confidence: ['95', "This answer is based on direct mentions and analyses of biomarker combinations in the context of the study's objectives and results."]%)_

  - **Survival analysis:** Univariable survival analysis was performed for L1CAM, PR, ER, STMN and PTEN. L1CAM overexpression was associated with worse outcomes (OS, DSS, PFS). For L1CAM (0-2 years), HRs were 4.22 (OS), 5.11 (DSS) and 4.51 (PFS) respectively. For PR positive tumors, OS, DSS, and PFS were 0.45, 0.39, and 0.32, respectively. For ER positive tumors from 0 to 2 years, OS, DSS, and PFS were 0.40, 0.30, and 0.52, respectively. PTEN loss was associated with PFS only (HR 0.60).

Multivariable analysis demonstrated that ProMisE molecular subtype maintained prognostic significance for DSS and PFS when correcting for each IHC biomarker.  Age maintained an association with OS only. Among all the biomarkers tested, only ER was significantly associated with outcome when corrected for other prognostic parameters. Between 0 and 2 years after surgery, ER positivity was associated with better DSS (p = 0.057), while after 2 years, high ER expression correlated with worse overall and disease specific survival (p≤0.002). Age remained associated with OS when corrected for each additional IHC biomarker. _(Confidence: ['100', 'Extracted the information directly from the text, no interpretation was needed.']%)_

  - **Confounding factors:** Yes, confounding factors such as age, BMI, stage, grade, histotype, LVSI, nodal status, treatment and myometrial invasion were considered. However, the number of different combinations of biomarkers analyzed together is not explicitly stated in the paper. _(Confidence: ['90', 'The paper explicitly mentions performing multivariable Cox regression analysis to account for confounding factors like age, BMI, stage, grade, histotype, LVSI and so on. The number of combinations are not clear.']%)_

  - **Primary biomarker:** L1CAM _(Confidence: ['95', 'L1CAM is mentioned in the title of the paper and is discussed in detail throughout the abstract, introduction, and results.']%)_

  - **Key Findings:** Testing L1CAM, PR, ER, STMN, and PTEN IHC biomarkers across all ECs does not appear to add prognostic value over ProMisE classification alone. Potential value added within molecular subtypes associated with intermediate outcomes may justify further studies on L1CAM and hormone receptor status specifically in the MMR-D and p53wt subtypes. _(Confidence: ['90', 'The text was taken directly from the summary and conclusions presented in the research paper.']%)_

---

**File:** `gs://tlab-extractionbucket/papers/S024_Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer- A TransPORTEC initiative.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** Markers of the p53 pathway further refine molecular profiling in high-risk endometrial cancer: A TransPORTEC initiative _(Confidence: ['100', 'The title is clearly visible and identifiable at the top of the page.']%)_

  - **Analysed Biomarkers:** p53, p21, and mdm2 _(Confidence: ['95', 'These biomarkers are most significant, based on their presence in the abstract, methods, and results, indicating their central role in the analysis.']%)_

  - **Biomarker combinations:** The research paper analyzed the following biomarker combinations: p53/mdm2 and p53/pp63. Additionally, the study investigated p53 with downstream markers such as p21, mdm2 and pp63. _(Confidence: ['100', 'The paper explicitly mentions these combinations when discussing independent prognostic factors and survival analysis.']%)_

  - **Survival analysis:** The paper presents univariable survival analyses, where Kaplan-Meier testing was used for overall survival analysis. The survival variables tested included p53 status, p21 expression, mdm2 expression, and pp63 expression. High expression of pp63 and mdm2 was associated with significantly worse overall survival (HRs 5.93 and 7.48, respectively; p<0.005), while high p21 expression was associated with fewer deaths (HR 0.37, p<0.005). A multivariable Cox Proportional Hazards Regression identified mdm2 as an independent prognostic factor. Stepwise regression suggested p53/mdm2 or p53/pp63 combinations act as independent variables. The combination of p53 wildtype and pp63 negative was associated with exceptionally good overall survival. _(Confidence: ['100', 'The information is directly stated in the results section.']%)_

  - **Confounding factors:** Age was considered a prognostic factor in recurrence-free survival, and Cox Proportional Hazards Regression identified MDM2 as an independent prognostic factor. Forward stepwise regression suggests that combinations of p53/mdm2 or p53/pp63 act as independent variables. Different combinations of biomarkers that were analyzed together are: p53/mdm2 and p53/pp63. _(Confidence: ['95', 'The text explicitly mentions age as a factor considered in the survival analysis and then identifies combinations of biomarkers analyzed together.']%)_

  - **Primary biomarker:** p53 _(Confidence: ['95', 'p53 is the primary biomarker because the title includes "Markers of the p53 pathway" and the abstract says "Here we attempted to further refine molecular classifications using markers of the p53 pathway."']%)_

  - **Key Findings:** Being marker positive for pp63 or mdm2 was associated with a significantly increased likelihood of dying, [hazard ratios 5.93 (95% CI 2.37-7.27) and 7.48 (95% CI 3.04-9.39), respectively]. _(Confidence: ['95', 'The finding is directly stated in the results section of the paper with clear metrics (hazard ratios and confidence intervals) and strong statistical significance.']%)_

---

**File:** `gs://tlab-extractionbucket/papers/S025_Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** Endometrial Carcinomas with POLE Exonuclease Domain Mutations Have a Favorable Prognosis _(Confidence: ['100', 'The title is clearly visible at the top of the first page of the PDF document.']%)_

  - **Analysed Biomarkers:** POLE, p53, MMR _(Confidence: ['90', 'POLE is mentioned in the title, abstract, and throughout the study as the primary biomarker of interest; p53 and MMR are key tumor suppressor genes and repair mechanisms respectively.']%)_

  - **Biomarker combinations:** The study combines clinicopathologic variables (stage, tumor grade, presence of lymphovascular space invasion (LVSI), histotype and grade) and POLE mutation status to assess patient outcomes and prognosis. Adjuvant treatment (chemotherapy or radiotherapy) and POLE mutational status was studied as well. _(Confidence: ['100', 'The information about clinicopathologic variables and POLE mutation status is explicitly stated in the abstract and throughout the paper, especially in the Results and Statistical Analysis sections.']%)_

  - **Survival analysis:** The study performed univariable and multivariable survival analyses to determine the effect of POLE mutation status on PFS, DSS, and OS.

**Univariable Analysis:**
POLE-mutated tumors were found to be significantly associated with improved PFS (HR, 0.16; 95% CI, 0.02-0.58; P < 0.001), DSS (HR, 0.26; 95% CI, 0.05-0.76; P = 0.005), and OS (HR, 0.35; 95% CI, 0.12-0.81; P = 0.006).
For grade 3 tumors only, women with tumors harboring POLE mutations demonstrated significantly improved univariable PFS (HR, 0.14; 95% CI, 0.02-0.49; LRT P < 0.001), DSS (HR, 0.14; 95% CI, 0.02-0.52; LRT P < 0.001), and OS (HR, 0.29; 95% CI, 0.08-0.74; LRT P = 0.003).

**Multivariable Analysis:**
In multivariable analysis for all cases, POLE was associated with improved PFS (HR, 0.22; 95% CI, 0.02-0.83; P = 0.010), but not with DSS (HR, 0.48; 95% CI, 0.1-1.48; P=0.1452) or OS (HR, 0.69; 95% CI, 0.22-1.67; P = 0.332).
In multivariable analysis for grade 3 tumors only, the mutational status of POLE was associated with an improved DSS (HR, 0.34; 95% CI, 0.04-1.33; LRT P = 0.073) and PFS (HR, 0.26; 95% CI, 0.03-1; LRT P = 0.025). _(Confidence: ['100', 'This entity was extracted from multiple parts of the document, and the information matches what was specified in the prompt.']%)_

  - **Confounding factors:** Yes, age, stage, and histotype were considered as confounding factors in the survival analysis of POLE-mutated endometrial carcinomas. The study analyzed the effect of POLE mutations on clinical outcomes and adjusted for these clinicopathological variables. Single biomarker combinations were analyzed in the univariable analysis and multiple in the multivariable. _(Confidence: ['95', 'The abstract mentions univariable and multivariable analyses and the article reports on age, stage, and histotype.']%)_

  - **Primary biomarker:** POLE exonuclease domain mutations (EDM) _(Confidence: ['95', 'The title of the article specifically mentions POLE Exonuclease Domain Mutations and throughout the paper, this is the main biomarker being investigated.']%)_

  - **Key Findings:** POLE-mutated endometrial carcinomas had significantly improved outcomes compared with patients with no EDMs for PFS, DSS, and OS. In multivariable analysis, POLE EDMs were only significantly associated with improved PFS. Meta-analysis revealed an association between POLE EDMs and improved PFS and DSS with pooled HRs 0.34 and 0.35, respectively. _(Confidence: ['95', 'The findings are clearly outlined in the results section.']%)_

---

**File:** `gs://tlab-extractionbucket/papers/S30_Integrated genomic characterization of endometrial carcinoma.pdf`

  - **Status:** <font color='green'>Success</font>

  - **Title of Paper:** Integrated Genomic Characterization of Endometrial Carcinoma _(Confidence: ['100', 'The title is clearly stated at the beginning of the document.']%)_

  - **Analysed Biomarkers:** POLE, TP53, PTEN _(Confidence: ['90', 'The abstract highlights the biomarkers POLE as a newly identified hotspot mutation, and TP53 and PTEN are found frequently throughout the text as commonly mutated genes.']%)_

  - **Biomarker combinations:** PTEN, CTNNB1, PIK3CA, ARID1A, and KRAS were studied together in relation to endometrioid tumors. TP53, PIK3CA, and PPP2R1A were studied together in relation to Type II tumors. Mutation rates in POLE mutant endometrial included PTEN, PIK3R1, PIK3CA, FBXW7, and KRAS. PTEN, PIK3CA and PIK3R1 and found co-occuring in the MSI and CN low subgroups. _(Confidence: ['90', 'The information was explicitly stated and studied together in the text.']%)_

  - **Survival analysis:** The research paper mentions progression-free survival (PFS) analyses in relation to copy number clusters and POLE mutations but does not present the p-values or the biomarkers used in multivariable analysis. For example, the paper states, "Copy number clusters 2 and 3 consisted mainly of endometrioid tumors, distinguished by more frequent 1q amplification in cluster 3 than cluster 2 (100% of cluster 3 tumors vs. 33% of cluster 2 tumors) and worse progression-free survival (PFS, P=0.003, log-rank vs. clusters 1 and 2; Fig. 1b)." It also states, "The ultra-mutated group consisted of 17 (7%) tumors exemplified by an increased C→A transversion frequency, all with mutations in the exonuclease domain of POLE, and an improved progression-free survival (Fig. 2a and 2c)." _(Confidence: ['80', 'The text mentions survival analysis being performed and indicates log-rank p-values, however, further details regarding the specific details of univariable and multivariable analysis are not given.']%)_

  - **Confounding factors:** No. The paper does not explicitly state that confounding factors were considered in the survival analysis. However, it does state that clinical and pathologic characteristics of the samples were representative of the population of interest (Supplementary Table 1.1). Also, four different combinations of biomarkers, as identified in Figure 2, were analyzed. _(Confidence: ['75', 'While the paper does not explicitly mention correcting for confounding factors in the survival analysis, it thoroughly integrates genomic, transcriptomic, and proteomic data to characterize endometrial carcinoma subtypes. It may be considered that correcting for these characteristics when creating the four different groups would then be considered correcting for confounding factors.']%)_

  - **Primary biomarker:** POLE _(Confidence: ['90', 'POLE mutations were emphasized throughout the paper, including classification into POLE ultramutated tumors.']%)_

  - **Key Findings:** Uterine serous tumors and ~25% of high-grade endometrioid tumors have extensive copy number alterations, few DNA methylation changes, low ER/PR levels, and frequent TP53 mutations. Most endometrioid tumors have few copy number alterations or TP53 mutations but frequent mutations in PTEN, CTNNB1, PIK3CA, ARIDIA, KRAS and novel mutations in the SWI/SNF gene ARID5B. A subset of endometrioid tumors identified had a dramatically increased transversion mutation frequency, and newly identified hotspot mutations in POLE. Results classified endometrial cancers into four categories: POLE ultramutated, microsatellite instability hypermutated, copy number low, and copy number high. Uterine serous carcinomas share genomic features with ovarian serous and basal-like breast carcinomas. The genomic features of endometrial carcinomas permit a reclassification that may impact post-surgical adjuvant treatment for women with aggressive tumors. _(Confidence: ['100', 'This text is from the summary section of the paper so is considered a key finding']%)_

---

In [ ]:
# @title ## MEREDITH Extractor (S2)

from IPython.display import display, Markdown
import time
from io import BytesIO
from PyPDF2 import PdfReader
import re
import textwrap
import google.generativeai as genai

genai.configure(api_key='')
model = genai.GenerativeModel("gemini-2.0-flash-001")

# Custom biomarker follow-up prompts
BIOMARKER_ENTITIES_TO_EXTRACT = {
      "Individual gene markers or biomarker signatures (univariate)": "Extract and list the individual gene markers tested within the study either by biomarker name or official gene name.",
     "Biomarker signatures (multivariable)": "Identify and extract the multivariable analysis conducted with each biomarker. For example, whether positive vs negative expression was tested, mutant vs wildtype, mutational status within subgroup, or deficient (d) vs proficient.",
     "Within the context of ProMisE": "Given the biomarker, determine if it is used in the ProMisE molecular classification of endometrial cancer. ProMisE uses three biomarker categories in sequence:\n\nMismatch Repair (MMR) proteins: MLH1, MSH2, MSH6, PMS2\n\nPOLE exonuclease domain mutations (EDM)\n\np53 immunohistochemistry (IHC)\n\nReturn 'Yes' if the biomarker belongs to one of these three categories, otherwise return 'No'.",
   # "Biomarker combinations": "Based on the biomarkers studied in this paper, what combinations of biomarkers were analyzed together in the same context (e.g., same figure, table, or statistical model)?",
   # "Survival analysis": "For each combination of biomarkers analyzed in this study, was a survival analysis (e.g., overall survival, progression-free survival) performed? If yes, summarize the result briefly for each combination.",
   # "Confounding factors": "Were any confounding factors (e.g., age, stage, histotype) considered in the survival analysis involving biomarker combinations? Return 'Yes' or 'No'. Also, how many different combinations of biomarkers were analyzed together?",
   # "Primary biomarker": "Identify the primary biomarker studied in this paper (i.e., the one most emphasized in title, abstract, or results). List additional biomarkers also studied and the total number of mentions or contexts for each (e.g., subgroup analysis, comparison).",
}

all_results = []
limit = 50

if not client:
    print("ERROR: GenAI Client not initialized. Please fix configuration.")
elif not storage_client:
    print("ERROR: GCS client not initialized. Please fix configuration.")
else:
    pdf_uris = list_pdfs_in_gcs(storage_client, GCS_BUCKET_NAME, GCS_PREFIX)

    pdf_files_to_process = [
        "S008_S100A1 Expression in Ovarian and Endometrial Endometrioid Carcinomas Is a Prognostic Indicator of Relapse-Free Survival.pdf",
        # Add other filenames if needed
    ]

    pdf_uris = [
        uri for uri in pdf_uris
        if any(uri.endswith(filename) for filename in pdf_files_to_process)
    ]

    if not pdf_uris:
        print("\nNo PDF files found or error listing files. Ensure configuration is correct and files exist.")
    else:
        print(f"\nStarting extraction for {len(pdf_uris)} PDF files using URIs...")

        for i, pdf_uri in enumerate(pdf_uris):
            if i > limit:
                break

            print(f"\n--- Processing file {i+1}/{len(pdf_uris)}: {pdf_uri} ---")
            file_result = {"pdf_uri": pdf_uri}

            # Step 1: Extract core entities
            entities_data = extract_entities_with_gemini_uri(pdf_uri, ENTITIES_TO_EXTRACT)
            file_result.update(entities_data)

            if "error" in entities_data:
                print(f"Extraction failed for {pdf_uri}: {entities_data['error']}")
            else:
                print(f"Extraction successful for {pdf_uri}.")

                # Step 2: Biomarker follow-up questions
                raw_biomarkers = entities_data.get("Analysed Biomarkers", "")

                # Improved parsing of biomarkers to avoid splitting gene names
                if isinstance(raw_biomarkers, str):
                    if "," in raw_biomarkers:
                        biomarkers = [b.strip() for b in raw_biomarkers.split(",") if b.strip()]
                    else:
                        biomarkers = [raw_biomarkers.strip()]
                elif isinstance(raw_biomarkers, list):
                    biomarkers = [b.strip() for b in raw_biomarkers if b.strip()]
                else:
                    biomarkers = []

                biomarkers = list(dict.fromkeys(biomarkers))  # Deduplicate preserving order

                # 🔸 NEW: Get full paper text from GCS and extract text
                try:
                    def extract_text_from_gcs(storage_client, gcs_uri):
                        from PyPDF2 import PdfReader
                        from io import BytesIO
                        bucket_name, path = gcs_uri.replace("gs://", "").split("/", 1)
                        bucket = storage_client.bucket(bucket_name)
                        blob = bucket.blob(path)
                        pdf_bytes = blob.download_as_bytes()
                        reader = PdfReader(BytesIO(pdf_bytes))
                        return "".join([page.extract_text() or "" for page in reader.pages])

                    pdf_text = extract_text_from_gcs(storage_client, pdf_uri)
                except Exception as e:
                    pdf_text = ""
                    print(f"[ERROR] Failed to extract PDF text for {pdf_uri}: {e}")

                biomarker_results = []
                paper_title = entities_data.get("Title of Paper", "this study")

                for biomarker in biomarkers:
                    for label, prompt_template in BIOMARKER_ENTITIES_TO_EXTRACT.items():
                        formatted_prompt = (
                        f"In the context of the following study text, "
                        f"regarding the biomarker '{biomarker}':\n\n{prompt_template}\n\n"
                        f"Please respond in 1–2 sentences without any explanation. "
                        f"Also provide a confidence score (0–100) on a new line labeled 'Confidence Score:' and a short, one sentence rationale for the given confidence score.\n\n"
                        f"{pdf_text[:8000]}"
                    )

                        try:
                            response = model.generate_content(formatted_prompt)
                            time.sleep(1.5)

                            response_text = getattr(response, "text", None)
                            if not response_text:
                                raise ValueError("Gemini response has no text.")

                            match = re.search(r"confidence score[^0-9]*([0-9]{1,3})", response_text, re.IGNORECASE)
                            confidence = int(match.group(1)) if match else None

                            biomarker_results.append({
                                "biomarker": biomarker,
                                "label": label,
                                "prompt": formatted_prompt,
                                "response": response_text.strip(),
                                "confidence": confidence
                            })

                        except Exception as e:
                            biomarker_results.append({
                                "biomarker": biomarker,
                                "label": label,
                                "prompt": formatted_prompt,
                                "response": f"ERROR: {str(e)}"
                            })

                file_result["biomarker_followups"] = biomarker_results

            all_results.append(file_result)


print(f"\n--- Extracted Information ({len(all_results)} files processed) ---")

if not all_results:
    print("No results were generated. Please check previous cell outputs for errors.")
else:
    for result in all_results:
        title = result.get("Title of Paper", "N/A")
        raw_biomarkers = result.get("Analysed Biomarkers", "")

        # Format biomarkers nicely for display (reuse parsing logic)
        if isinstance(raw_biomarkers, str):
            if "," in raw_biomarkers:
                biomarkers = [b.strip() for b in raw_biomarkers.split(",") if b.strip()]
            else:
                biomarkers = [raw_biomarkers.strip()]
        elif isinstance(raw_biomarkers, list):
            biomarkers = [b.strip() for b in raw_biomarkers if b.strip()]
        else:
            biomarkers = []

        biomarkers = list(dict.fromkeys(biomarkers))

        followups = result.get("biomarker_followups", [])

        display(Markdown(f"### **Title of paper:**\n{title}"))
        display(Markdown(f"**Analysed biomarkers:** {', '.join(biomarkers) if biomarkers else 'None'}"))

        # Group responses by biomarker
        biomarker_grouped = {}
        for entry in followups:
            biomarker = entry["biomarker"]
            if biomarker not in biomarker_grouped:
                biomarker_grouped[biomarker] = {}
            biomarker_grouped[biomarker][entry["label"]] = entry["response"]

        for biomarker, responses in biomarker_grouped.items():
            display(Markdown(f"\n---\n### **{biomarker}:**"))
            for label in BIOMARKER_ENTITIES_TO_EXTRACT:
                response_text = responses.get(label, "Not found.")
                display(Markdown(f"**{label}:**\n{response_text}"))

        display(Markdown("---\n"))

ModuleNotFoundError: No module named 'PyPDF2'

In [ ]:
import csv
import pandas as pd

# Replace this with your actual list of dictionaries containing extracted data
# For example: extracted_data = [{'Title of Paper': '...', 'Author list': '...', ...}, ...]
extracted_data = all_results
csv_file_path = 'extracted_results.csv'

# Get all unique fieldnames from your data
fieldnames = list({key for d in extracted_data for key in d.keys()})

with open(csv_file_path, mode='w', newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for row in extracted_data:
        writer.writerow(row)

print(f"\nExported extracted results to {csv_file_path}")

Exported extracted results to extracted_results.csv

In [ ]:
#S1 data visualization
import pandas as pd

# Convert data to DataFrame and save to CSV
df = pd.DataFrame(extracted_data)
df.to_csv('extracted_results.csv', index=False)

# Set row numbers (index) to start at 1
df.index = range(1, len(df) + 1)

# Display all rows
pd.set_option('display.max_rows', None)
df

,pdf_uri,% of participants with clinicopathological features (Stage I or II)
1,gs://tlab-extractionbucket3/papers3/S023_Frequ...,"{'value': '68%', 'confidence': ['90', 'The tex..."
2,gs://tlab-extractionbucket3/papers3/S024_Marke...,"{'value': 'n/a', 'confidence': ['0', 'The pape..."
3,gs://tlab-extractionbucket3/papers3/S025_Endom...,"{'value': '95%', 'confidence': ['95', 'The tex..."
4,gs://tlab-extractionbucket3/papers3/S026_Assoc...,"{'value': 'n/a', 'confidence': ['0', 'The pape..."
5,gs://tlab-extractionbucket3/papers3/S027_Sex S...,"{'value': '13%', 'confidence': ['100', 'This v..."
6,gs://tlab-extractionbucket3/papers3/S028_PIK3C...,"{'value': 'n/a', 'confidence': ['0', 'The pape..."
7,gs://tlab-extractionbucket3/papers3/S029_MMR d...,{'value': '46 Stage I + 13 Stage II / 102 tota...
8,gs://tlab-extractionbucket3/papers3/S30_Integr...,"{'value': 'n/a', 'confidence': ['0', 'I did no..."
9,gs://tlab-extractionbucket3/papers3/S31_ARID1A...,"{'value': 'n/a', 'confidence': ['0', 'The pape..."
10,gs://tlab-extractionbucket3/papers3/S32_Necros...,"{'value': '81%', 'confidence': ['100', '58% + ..."
11,gs://tlab-extractionbucket3/papers3/S33_Low me...,"{'value': 'n/a', 'confidence': ['0', 'The perc..."
12,gs://tlab-extractionbucket3/papers3/S34_Expres...,"{'value': '76.1%', 'confidence': ['99', 'The p..."
13,"gs://tlab-extractionbucket3/papers3/S35_Cyr61,...","{'value': 'n/a', 'confidence': ['0', 'The pape..."
14,gs://tlab-extractionbucket3/papers3/S36_Promot...,"{'value': 'n/a', 'confidence': ['0', 'The pape..."
15,gs://tlab-extractionbucket3/papers3/S37_Cathep...,"{'value': '80%', 'confidence': ['100', 'The va..."
16,gs://tlab-extractionbucket3/papers3/S38_Invers...,"{'value': '76.9%', 'confidence': ['100', 'The ..."
17,gs://tlab-extractionbucket3/papers3/S39_Expres...,"{'value': 'n/a', 'confidence': ['0', 'I am una..."
18,gs://tlab-extractionbucket3/papers3/S40_Claudi...,"{'value': '97%', 'confidence': ['100', 'The st..."
19,gs://tlab-extractionbucket3/papers3/S41_GATA3 ...,"{'value': '81%', 'confidence': ['100', 'The va..."
20,gs://tlab-extractionbucket3/papers3/S42_Expres...,"{'value': '57%', 'confidence': ['100', 'The do..."
21,gs://tlab-extractionbucket3/papers3/S43_Proges...,"{'value': '75.7%', 'confidence': ['100', 'The ..."
22,gs://tlab-extractionbucket3/papers3/S44_Clinic...,{'value': '39% (24% Stage I and 15% Stage II)'...
23,gs://tlab-extractionbucket3/papers3/S45_p53 mu...,"{'value': '52.9%', 'confidence': ['95', 'The t..."
24,gs://tlab-extractionbucket3/papers3/S46_Charac...,"{'value': '66.7%', 'confidence': ['100', 'The ..."
25,gs://tlab-extractionbucket3/papers3/S47_CD103 ...,"{'value': '69.2%', 'confidence': ['100', 'The ..."
26,gs://tlab-extractionbucket3/papers3/S48_Progno...,"{'value': '54.3%', 'confidence': ['95', 'The s..."
27,gs://tlab-extractionbucket3/papers3/S49_L1CAM ...,"{'value': '81.6%', 'confidence': ['100', 'This..."
28,gs://tlab-extractionbucket3/papers3/S50_Silenc...,"{'value': '73.33%', 'confidence': ['99', 'The ..."
29,gs://tlab-extractionbucket3/papers3/S51_DNA mi...,"{'value': '84.3%', 'confidence': ['90', 'The t..."
30,gs://tlab-extractionbucket3/papers3/S52_Expres...,"{'value': 'n/a', 'confidence': ['0', 'This inf..."
31,gs://tlab-extractionbucket3/papers3/S53_ARID1A...,"{'value': '63%', 'confidence': ['100', 'The va..."
32,gs://tlab-extractionbucket3/papers3/S54_L1 cel...,"{'value': 'n/a', 'confidence': ['0', 'The text..."
33,gs://tlab-extractionbucket3/papers3/S55_Eviden...,{'value': 'Among patients with FIGO stage I/II...
34,gs://tlab-extractionbucket3/papers3/S56_PIK3CA...,"{'value': 'n/a', 'confidence': ['0', 'There is..."
35,gs://tlab-extractionbucket3/papers3/S57_Immuno...,"{'value': 'n/a', 'confidence': ['0', 'The perc..."
36,gs://tlab-extractionbucket3/papers3/S58_The au...,"{'value': 'n/a', 'confidence': ['0', 'This inf..."
37,gs://tlab-extractionbucket3/papers3/S59_Stathm...,"{'value': '72.9%', 'confidence': ['100', 'This..."
38,gs://tlab-extractionbucket3/papers3/S60_IGF2BP...,"{'value': '80%', 'confidence': ['85', 'The tex..."
39,gs://tlab-extractionbucket3/papers3/S61_EphA2 ...,"{'value': '78%', 'confidence': ['100', 'The va..."
40,gs://tlab-extractionbucket3/papers3/S62_Aromat...,"{'value': '76.1%', 'confidence': ['100', 'The ..."
41,gs://tlab-extractionbucket3/papers3/S63_Expres...,"{'value': '32', 'confidence': ['100', 'The exa..."
42,gs://tlab-extractionbucket3/papers3/S64_Ovaria...,"{'value': '83.2%', 'confidence': ['100', 'The ..."
43,gs://tlab-extractionbucket3/papers3/S65_Prosta...,"{'value': '64%', 'confidence': ['90', 'The pap..."
44,gs://tlab-extractionbucket3/papers3/S66_GPR30-...,"{'value': '63.8%', 'confidence': ['100', 'The ..."
45,gs://tlab-extractionbucket3/papers3/S67_Activa...,"{'value': '83%', 'confidence': ['95', 'The tex..."
46,gs://tlab-extractionbucket3/papers3/S68_HER-2 ...,"{'value': '60%', 'confidence': ['100', 'The 'S..."
47,gs://tlab-extractionbucket3/papers3/S69_Ezrin ...,"{'value': 'n/a', 'confidence': ['0', 'The pape..."
48,gs://tlab-extractionbucket3/papers3/S70_Replic...,"{'value': 'n/a', 'confidence': ['0', 'This inf..."
49,gs://tlab-extractionbucket3/papers3/S71_Intrat...,"{'value': 'n/a', 'confidence': ['0', 'This inf..."
50,gs://tlab-extractionbucket3/papers3/S72_L1 exp...,"{'value': '22%', 'confidence': ['95', 'The pap..."
51,gs://tlab-extractionbucket3/papers3/S73_Expres...,"{'value': '56%', 'confidence': ['100', 'The nu..."
52,gs://tlab-extractionbucket3/papers3/S74_Associ...,"{'value': 'n/a', 'confidence': ['0', 'The stud..."
53,gs://tlab-extractionbucket3/papers3/S75_Immuno...,"{'value': '31.6%', 'confidence': ['100', 'The ..."
54,gs://tlab-extractionbucket3/papers3/S76_Final ...,"{'value': '66.9%', 'confidence': ['95', '276 p..."
55,gs://tlab-extractionbucket3/papers3/S77_Improv...,"{'value': 'n/a', 'confidence': ['0', 'The info..."
56,gs://tlab-extractionbucket3/papers3/S78_L1CAM ...,"{'value': '86%', 'confidence': ['100', 'Calcul..."
57,gs://tlab-extractionbucket3/papers3/S79_A clin...,"{'value': 'n/a', 'confidence': ['0', 'The perc..."
58,gs://tlab-extractionbucket3/papers3/S80_Refini...,"{'value': '54%', 'confidence': ['100', 'This i..."
59,gs://tlab-extractionbucket3/papers3/S81_POLE P...,"{'value': 'n/a', 'confidence': ['0', 'The pape..."
60,gs://tlab-extractionbucket3/papers3/S82_Progno...,"{'value': 'n/a', 'confidence': ['0', 'Informat..."
61,gs://tlab-extractionbucket3/papers3/S83_L1CAM ...,"{'value': 'n/a', 'confidence': ['0', 'This inf..."
62,gs://tlab-extractionbucket3/papers3/S84_Lack o...,"{'value': 'n/a', 'confidence': ['0', 'I am una..."
63,gs://tlab-extractionbucket3/papers3/S85_Diagno...,"{'value': 'n/a', 'confidence': ['0', 'There is..."
64,gs://tlab-extractionbucket3/papers3/S86_Deregu...,"{'value': 'n/a', 'confidence': ['0', 'The arti..."
65,gs://tlab-extractionbucket3/papers3/S87_Progno...,"{'value': '56.9%', 'confidence': ['95', 'The s..."
66,gs://tlab-extractionbucket3/papers3/S88_Epigen...,"{'value': 'n/a', 'confidence': ['0', 'The stud..."
67,gs://tlab-extractionbucket3/papers3/S89_The re...,"{'value': 'n/a', 'confidence': ['0', 'The stud..."
68,gs://tlab-extractionbucket3/papers3/S90_Immuno...,{'value': 'The tumor stage is significantly as...
69,gs://tlab-extractionbucket3/papers3/S91_Progno...,"{'value': 'n/a', 'confidence': ['0', 'This inf..."
70,gs://tlab-extractionbucket3/papers3/S92_Role o...,"{'value': 'n/a', 'confidence': ['0', 'The pape..."
71,gs://tlab-extractionbucket3/papers3/S93_Angiog...,"{'value': '84.2%', 'confidence': ['95', 'This ..."
72,gs://tlab-extractionbucket3/papers3/S94_PTEN m...,"{'value': '85%', 'confidence': ['95', 'The tex..."
73,gs://tlab-extractionbucket3/papers3/S95_Urokin...,"{'value': '45%', 'confidence': ['90', 'The pap..."
74,gs://tlab-extractionbucket3/papers3/S96_Interp...,"{'value': '87%', 'confidence': ['100', '152 ou..."
75,gs://tlab-extractionbucket3/papers3/S97_Potent...,"{'value': 'n/a', 'confidence': ['0', 'This inf..."
76,gs://tlab-extractionbucket3/papers3/S98_Amplif...,"{'value': 'n/a', 'confidence': ['0', 'The docu..."
77,gs://tlab-extractionbucket3/papers3/S99_Assess...,"{'value': 'n/a', 'confidence': ['0', 'There is..."

In [ ]:
#S2 Data visualization
import pandas as pd

# Prepare structured flat list for DataFrame
flattened_rows = []

for result in all_results:
    title = result.get("Title of Paper", "N/A")
    all_biomarkers = result.get("Analysed Biomarkers", [])
    followups = result.get("biomarker_followups", [])

    if isinstance(all_biomarkers, list):
        analysed_str = ", ".join(all_biomarkers)
    else:
        analysed_str = str(all_biomarkers)

    # Group followups by biomarker
    grouped = {}
    for entry in followups:
        biomarker = entry["biomarker"]
        if biomarker not in grouped:
            grouped[biomarker] = {}
        grouped[biomarker][entry["label"]] = entry["response"]

    for biomarker, labels in grouped.items():
        row = {
            "Title of Paper": title,
            "Analysed Biomarkers": analysed_str,
            "Biomarker": biomarker,
            "Univariate": labels.get("Individual gene markers or biomarker signatures (univariate)", "Not found."),
            "Multivariate": labels.get("Biomarker signatures (multivariable)", "Not found."),
            "Within the context of ProMisE": labels.get("Within the context of ProMisE", "Not found.")
        }
        flattened_rows.append(row)

# Create DataFrame
df = pd.DataFrame(flattened_rows)

# Optional: reset index starting at 1
df.index = range(1, len(df) + 1)

# Optional: display all rows
pd.set_option('display.max_rows', None)

# Save to CSV
df.to_csv("extracted_results.csv", index=False)

# Display the DataFrame
df

,Title of Paper,Analysed Biomarkers,Biomarker,Univariate,Multivariate,Within the context of ProMisE
1,S100A1 Expression in Ovarian and Endometrial E...,S100A1,S100A1,"Based on the provided text, the gene markers t...","Based on the text provided, here's the multiva...",No
2,POLE exonuclease domain mutation predicts long...,"POLE, MSH6, PIK3CA",POLE,"Based on the provided text, the individual gen...","Based on the provided text, here's the multiva...",Yes
3,POLE exonuclease domain mutation predicts long...,"POLE, MSH6, PIK3CA",MSH6,"Based on the provided text, the gene markers t...","Based on the provided text, here's the multiva...",Yes
4,POLE exonuclease domain mutation predicts long...,"POLE, MSH6, PIK3CA",PIK3CA,"Based on the provided text, the following gene...","Based on the provided text, here's the multiva...",No
5,Molecular classification defines outcomes and ...,"MMR, POLE, p53",MMR,"Based on the provided text, the MMR biomarker ...","Based on the provided text, here's the informa...",Yes
6,Molecular classification defines outcomes and ...,"MMR, POLE, p53",POLE,"Based on the provided text, the individual gen...",ERROR: 429 POST https://generativelanguage.goo...,ERROR: 429 POST https://generativelanguage.goo...
7,Molecular classification defines outcomes and ...,"MMR, POLE, p53",p53,"Based on the provided text, the following gene...",ERROR: 429 POST https://generativelanguage.goo...,ERROR: 429 POST https://generativelanguage.goo...